### ISSUE TITLE
getting the gpu solver running

### ISSUE THREAD

**Issue by kalmarek** [cvxgrp/scs#103]
I tried to compile SCS with CUDA with
```
make DLONG=1 USE_OPENMP=1 USE_LAPACK=1 BLAS64=1 BLASSUFFIX=_64_ EXTRA_VERBOSE=2 default gpu
```
I've edited `scs.mk` so that
```
CUDADIR = /opt/cuda
CULDFLAGS = -L$(CUDADIR)/lib64
CULDFLAGS += -lcudart -lcublas -lcusparse
CUDAFLAGS = $(CFLAGS) -I$(CUDADIR)/include
```
(I also use my own BLAS but that shouldn't matter?)

everything compiles fine, but when I run
```
LD_LIBRARY_PATH=$PATH_TO_BLAS ./out/demo_socp_gpu 10
```
I get https://gist.github.com/kalmarek/15d763a70a62322f6748df52ea572707
(just before "transposing A" which I see on `demo_socp_indirect`)

**Comment by Cerebrock** [comment]
I've been failing to use SCS + GPU as well https://stackoverflow.com/questions/52579531/how-to-install-cvxpy-scs-to-use-with-gpu

**Comment by cynnjjs** [comment]
@Cerebrock I'm having the same problem here. When I run problem.solve with gpu=False, I get status = solved, but with gpu=True I get Unbounded. I'm simply running the following testing program:

m = 30
n = 20
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)
x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A*x - b))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)
result = prob.solve("SCS", gpu=False, verbose=True)

I tried the following setup, but it did not help:

python3 setup.py install --scs --gpu --int

How did you resolve the problem?

**Comment by kalmarek** [comment]
my problem was because of broken cuda installation; since there is another issue about unbounded solution I'm closing this
