### ISSUE TITLE
SCS(set_default_settings) 

### ISSUE THREAD

**Issue by kalmarek** [cvxgrp/scs#108]
This is a request for a breaking change.

Since You're preparing a new release (2.1.0) would it be possible to change
https://github.com/cvxgrp/scs/blob/4709f15587bf8b48a124e95e267df1071ad52633/src/util.c#L200
so that it operates directly on `ScsSettings` struct?

**Comment by bodono** [comment]
I can probably do that, but why do you need it? The reason for taking the data struct is in case (in the future) some of the default settings depend on problem data, e.g., it could be the case that some scale parameter might depend on the size of the data matrix.

**Comment by kalmarek** [comment]
ok, that is a very valid reason.

The reason why I asked for this is that in SCS.jl we need to first create dummy SCSData, populate its default settings and attach these to the actual problem, while overriding those provided by the user. 

https://github.com/JuliaOpt/SCS.jl/blob/master/src/types.jl#L73

Maybe You have a better idea how to do it?
(anyway it's just a minor annoyance)

**Comment by bodono** [comment]
I really don't know much about Julia, but it's strange to have to do it like that. In python, for example, we just set the default settings and then override them with whatever was actually specified by the user:

https://github.com/bodono/scs-python/blob/master/src/scsmodule.c#L312

Anyway, I'm going to close this but feel free to reopen if you feel strongly about it.

**Comment by kalmarek** [comment]
no, I don't feel strongly about this ;)

In SCS.jl there is separation between creating solvers instance (options are parsed) and solving (options are passed to scs): there is an `SCS.Optimizer` object which holds all the user input and it's nice for the user to throw an error upon its creation if a unrecognized option is passed.

anyway, it's ok to close this
