### ISSUE TITLE
Anderson acceleration error not silenced

### ISSUE THREAD

**Issue by SteveDiamond** [cvxgrp/scs#115]
Errors of the form "Error in AA type 1, iter: 36, info: 0, norm 1.23e+04" seem to print even when output is silenced. This breaks tests in cvxpy I have for solver verbosity.

**Comment by SteveDiamond** [comment]
This actually wasn't what was breaking my tests. I'm not totally sure if verbose is silencing the errors or not. I'll close the issue.

**Comment by bodono** [comment]
I silenced the error message anyway.
