### ISSUE TITLE
CVXPY>=1.24.0 install fails due to scs 2.1.1 release

### ISSUE THREAD

**Issue by cshartrand** [cvxgrp/scs#120]
The latest update of scs breaks installation of cvxpy

**Comment by cshartrand** [comment]
Issue is also for 2.1.0

**Comment by kalmarek** [comment]
I'm not sure about cvxpy internals, but  `SCS_Settings` got a new field https://github.com/cvxgrp/scs/blob/d2c1ae92b8c5c6d45406afd007d1ddad74635cfd/include/scs.h#L62
which will break existing wrappers interacting with it; 
you should file the issue in cvxpy i guess.

Do they really download the latest release blindly?

**Comment by bodono** [comment]
I don't think that the new field is the problem, see the other issue filed:https://github.com/bodono/scs-python/issues/19

I just reuploaded the pip release, so hopefully it is fixed now. Can you check and let me know?

**Comment by cshartrand** [comment]
Seems to have fixed my issue. For transparency sake, was attempting to install on a clean slate EMR instance. Error screenshots attached. Initial thoughts were that it was attempting to compile on the EMR without the proper tools to do so.

<img width="1564" alt="Screen Shot 2019-07-08 at 5 16 55 PM" src="https://user-images.githubusercontent.com/13841644/60847636-60fd3100-a1b1-11e9-9f83-3e196429f9b5.png">
<img width="1567" alt="Screen Shot 2019-07-08 at 5 17 14 PM" src="https://user-images.githubusercontent.com/13841644/60847637-6195c780-a1b1-11e9-9d9b-0a97164584f2.png">

**Comment by bodono** [comment]
Thanks for the update!

**Comment by smith4455** [comment]
Hi, 

I was wondering if this issue is really resolved. Because I have trouble installing cvxpy. When I try to install scs by itself I get this error:

<img width="1640" alt="Screen Shot 2019-07-15 at 4 56 41 PM" src="https://user-images.githubusercontent.com/15970659/61248843-f05e9300-a721-11e9-907e-24a5a7534d76.png">

**Comment by bodono** [comment]
That's a different issue, looks like your python install is broken. I would recommend getting a fresh anaconda install and using that.

**Comment by smith4455** [comment]
Refreshing my Anaconda and using Python 3.6 worked. Thank you
