### ISSUE TITLE
using $CUDA_PATH in scs.mk

### ISSUE THREAD

**Issue by kalmarek** [cvxgrp/scs#124]
how feasible (i.e. portable) is it? locally (on Linux) I have changed
`CULDFLAGS = -L/usr/local/cuda/lib` → `CULDFLAGS = -L$(CUDA_PATH)/lib` and
`CUDAFLAGS = $(CFLAGS) -I/usr/local/cuda/include -Wno-c++11-long-long` → `CUDAFLAGS = $(CFLAGS) -I$(CUDA_PATH)/include -Wno-c++11-long-long`

since standard cuda installation defines global `CUDA_PATH`. Would it work for other environments? (https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#build-customizations-for-existing-projects claims that the installer sets the env variable on Windows as well)

It doesn't seem to be the case on MacOS though. maybe in the `Darwin` section one could 
`ifeq ( $CUDA_PATH, )
CUDA_PATH=/usr/local/cuda
endif`
?

**Comment by bodono** [comment]
Good point, thanks for the tip, just submitted a change that does this!
