### ISSUE TITLE
Installation failed with MacOS  - python35-36 

### ISSUE THREAD

**Issue by skoudoro** [cvxgrp/scs#127]
Hi SCS Team, 

Thank you for this nice package. 

As you can see [here](https://dev.azure.com/skab12/dipy/_build/results?buildId=130&view=logs&jobId=946da724-5632-5f8c-8beb-fd3a3d446dcb&taskId=381d7de5-2cd2-5f07-4d7d-02c7e4e6abed&lineStart=220&lineEnd=221&colStart=1&colEnd=1), the package failed to compile on MacOS with python3.6 and python3.5.

Any idea on how to fix this point? is it expected?

Thank you.

ps:  `scs.__version__ = 2.1.1_2`

**Comment by bodono** [comment]
I can install SCS fine on my local machine with python 3.5 and 3.6 (and 3.7), and as you can see [here](https://travis-ci.org/bodono/scs-python) the travis tests are passing on mac with both python 3.5 and 3.6. Those tests are using SCS v 2.1.1_2. I can't tell what's going on with your build, but I would guess that something is broken in your toolchain.

**Comment by skoudoro** [comment]
ok, Thank you for the feedback, will look deeper in Azure pipelines
