### ISSUE TITLE
failed to install scs on macOS

### ISSUE THREAD

**Issue by lijuanLin** [cvxgrp/scs#131]
when I  run "pip install scs" in the terminal, I got the following error. hope you can help me solve this problem. thank you.

Collecting scs
  Using cached scs-2.1.1-2.tar.gz (157 kB)
Requirement already satisfied: numpy>=1.7 in /Users/linlijuan/anaconda3/lib/python3.6/site-packages (from scs) (1.18.1)
Requirement already satisfied: scipy>=0.13.2 in /Users/linlijuan/anaconda3/lib/python3.6/site-packages (from scs) (1.3.0)
Building wheels for collected packages: scs
  Building wheel for scs (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/linlijuan/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rh/t58tx0dd1sdbthz8zcncr5wc0000gn/T/pip-install-s2vhzrh_/scs/setup.py'"'"'; __file__='"'"'/private/var/folders/rh/t58tx0dd1sdbthz8zcncr5wc0000gn/T/pip-install-s2vhzrh_/scs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/rh/t58tx0dd1sdbthz8zcncr5wc0000gn/T/pip-wheel-49dkxflq
       cwd: /private/var/folders/rh/t58tx0dd1sdbthz8zcncr5wc0000gn/T/pip-install-s2vhzrh_/scs/
  Complete output (117 lines):
  Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, int32=False, scs=False)
  /Users/linlijuan/anaconda3/lib/python3.6/site-packages/setuptools/dist.py:481: UserWarning: The version specified ('2.1.1_2') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
    "details." % self.metadata.version
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/scs
  copying src/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/scs
  running build_ext
  blas_mkl_info:
    NOT AVAILABLE
  blis_info:
    NOT AVAILABLE
  openblas_info:
      libraries = ['openblas', 'openblas']
      library_dirs = ['/usr/local/lib']
      language = c
      define_macros = [('HAVE_CBLAS', None)]
  blas_opt_info:
      libraries = ['openblas', 'openblas']
      library_dirs = ['/usr/local/lib']
      language = c
      define_macros = [('HAVE_CBLAS', None)]
  lapack_mkl_info:
    NOT AVAILABLE
  openblas_lapack_info:
      libraries = ['openblas', 'openblas']
      library_dirs = ['/usr/local/lib']
      language = c
      define_macros = [('HAVE_CBLAS', None)]
  lapack_opt_info:
      libraries = ['openblas', 'openblas']
      library_dirs = ['/usr/local/lib']
      language = c
      define_macros = [('HAVE_CBLAS', None)]
  {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/linlijuan/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/usr/local/include', '/Users/linlijuan/anaconda3/include']}
  {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/linlijuan/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/usr/local/include', '/Users/linlijuan/anaconda3/include']}
  In file included from scs/src/linalg.c:1:0:
  scs/include/linalg.h:8:18: fatal error: math.h: No such file or directory
   #include <math.h>
                    ^
  In file included from scs/src/aa.c:1:0:
  scs/include/aa.h:8:19: fatal error: stdio.h: No such file or directory
   #include <stdio.h>
                     ^
  compilation terminated.
  compilation terminated.
  In file included from scs/include/cones.h:8:0,
                   from scs/src/cones.c:1:
  scs/include/glbopts.h:8:18: fatal error: math.h: No such file or directory
   #include <math.h>
                    ^
  compilation terminated.
  In file included from /Users/linlijuan/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                   from /Users/linlijuan/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                   from /Users/linlijuan/anaconda3/include/python3.6m/Python.h:11,
                   from src/scsmodule.c:1:
  /Users/linlijuan/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  scs/linsys/direct/external/amd/SuiteSparse_config.c:12:18: fatal error: math.h: No such file or directory
   #include <math.h>
                    ^
  compilation terminated.
  In file included from scs/src/scs.c:1:0:
  scs/include/scs.h:8:20: fatal error: string.h: No such file or directory
   #include <string.h>
                      ^
  compilation terminated.
  In file included from scs/linsys/amatrix.h:8:0,
                   from scs/linsys/common.h:8,
                   from scs/linsys/common.c:1:
  scs/include/glbopts.h:8:18: fatal error: math.h: No such file or directory
   #include <math.h>
                    ^
  compilation terminated.
  In file included from scs/linsys/direct/external/amd/amd_info.c:15:0:
  scs/linsys/direct/external/amd/amd_internal.h:50:20: fatal error: stdlib.h: No such file or directory
   #include <stdlib.h>
                      ^
  compilation terminated.
  In file included from scs/linsys/direct/external/amd/amd_defaults.c:15:0:
  scs/linsys/direct/external/amd/amd_internal.h:50:20: fatal error: stdlib.h: No such file or directory
   #include <stdlib.h>
                      ^
  compilation terminated.
  In file included from scs/linsys/direct/external/amd/amd_1.c:27:0:
  scs/linsys/direct/external/amd/amd_internal.h:50:20: fatal error: stdlib.h: No such file or directory
   #include <stdlib.h>
                      ^
  compilation terminated.
  In file included from scs/linsys/direct/external/amd/amd_valid.c:36:0:
  scs/linsys/direct/external/amd/amd_internal.h:50:20: fatal error: stdlib.h: No such file or directory
   #include <stdlib.h>
                      ^
  compilation terminated.
  In file included from scs/linsys/direct/external/amd/amd_aat.c:18:0:
  scs/linsys/direct/external/amd/amd_internal.h:50:20: fatal error: stdlib.h: No such file or directory
   #include <stdlib.h>
                      ^
  compilation terminated.
  In file included from scs/linsys/direct/external/amd/amd_order.c:15:0:
  scs/linsys/direct/external/amd/amd_internal.h:50:20: fatal error: stdlib.h: No such file or directory
   #include <stdlib.h>
                      ^
  compilation terminated.
  In file included from scs/linsys/direct/external/qdldl/qdldl_types.h:4:0,
                   from scs/linsys/direct/external/qdldl/qdldl.h:5,
                   from scs/linsys/direct/external/qdldl/qdldl.c:1:
  scs/include/glbopts.h:8:18: fatal error: math.h: No such file or directory
   #include <math.h>
                    ^
  compilation terminated.
  error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/linlijuan/anaconda3/include -arch x86_64 -I/Users/linlijuan/anaconda3/include -arch x86_64 -DPYTHON -DCTRLC=1 -DDLONG=1 -DCOPYAMATRIX -DUSE_LAPACK -DSCIPY_MKL_H -DHAVE_CBLAS -DSCIPY_MKL_H -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/direct/ -Iscs/linsys/direct/external/ -I/Users/linlijuan/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/usr/local/include -I/Users/linlijuan/anaconda3/include -I/usr/local/include -I/Users/linlijuan/anaconda3/include -I/Users/linlijuan/anaconda3/include/python3.6m -c scs/src/aa.c -o build/temp.macosx-10.7-x86_64-3.6/scs/src/aa.o -O3" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for scs

**Comment by bodono** [comment]
This is a problem with your MacOS install, try the steps here: https://github.com/RcppCore/Rcpp/issues/922
