### ISSUE TITLE
High average projection time

### ISSUE THREAD

**Issue by omart-59** [cvxgrp/scs#132]
I am using scs (via cvx in matlab) to find approximate solutions to a large scale semidefinite program. The program exhibits 3 semidefinite constraints hence I would expect that the algorithm performs 3 eigenvalue decompositions per iteration in order to project onto the corresponding cones. Example: with matrices of dimension 256 x 256 projecting 3 hermitian matrices onto the positive semidefinite cone takes typically around 0.02 - 0.03 s on my computer while the solver outputs an average projection time of 0.127 s. Where is this difference coming from? 

Here is the program in matlab (in the example with n=256, m=110, c0 and A0 constant and Qpt a linear matrix operation):

<pre><code>cvx_begin sdp

cvx_solver SCS
cvx_solver_settings('max_iters',100,'acceleration_lookback',10);

variable z(m,1)
variable X(n,n) hermitian

Atot = cvx(zeros(n));
for k = 1:m
    A = A + z(k)*reshape(A0(k,:),n,n);
end

minimize( real(z'*c0) )

subject to 

- X <= eye(n)
X <= eye(n)
A - Qpt(X) <= 0

cvx_end
</code></pre>

**Comment by bodono** [comment]
Can you output what SCS is saying when you turn on verbose=True? I presume you have linked against the MATLAB blas / lapack, and your timings are also from MATLAB?

**Comment by omart-59** [comment]
Yes, specifically I compare
<pre><code>
M=rand(256)+1i*rand(256);M = M + M';
tic
[U,D]=eig(M);
U*diag(max(diag(D),0))*U',n^2,1);
toc
</code></pre>
(I get typically less than 0.01 s) with the average projection time in the following output:
<pre><code>
Calling SCS 2.1.1: 394094 variables, 131072 equality constraints
------------------------------------------------------------
NOTE: custom settings have been set for this solver.
------------------------------------------------------------
----------------------------------------------------------------------------
	SCS v2.1.1 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 543232
eps = 1.49e-08, alpha = 1.50, max_iters = 100, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 131072, constraints m = 394094
Cones:	primal zero / dual free vars: 110
	sd vars: 393984, sd blks: 3
Setup time: 2.41e-01s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 9.84e-01  1.82e+00  9.83e-01 -4.54e+01  1.27e+01  2.03e-14  1.53e-01 
   100| 2.81e-04  3.53e-04  2.02e-03  1.39e+00  1.40e+00  6.73e-15  1.68e+01 
----------------------------------------------------------------------------
Status: Solved/Inaccurate
Hit max_iters, solution may be inaccurate, returning best found solution.
Timing: Solve time: 1.68e+01s
	Lin-sys: nnz in L factor: 1134709, avg solve time: 4.18e-003s
	Cones: avg projection time: 1.26e-001s
	Acceleration: avg step time: 2.65e-002s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 1.9509e-09, dist(y, K*) = 2.9445e-09, s'y/|s||y| = 1.9612e-13
primal res: |Ax + s - b|_2 / (1 + |b|_2) = 1.0276e-03
dual res:   |A'y + c|_2 / (1 + |c|_2) = 1.3945e-03
rel gap:    |c'x + b'y| / (1 + |c'x| + |b'y|) = 9.0577e-04
----------------------------------------------------------------------------
c'x = 1.3976, -b'y = 1.4010
============================================================================
------------------------------------------------------------
Status: Failed
Optimal value (cvx_optval): NaN
</code></pre>

**Comment by bodono** [comment]
Based on this : `sd vars: 393984, sd blks: 3`, it looks like SCS is getting passed 3  (512 x 512) sdp cone constraints (the formula is num_sd_blks * (num_vars^2 + num_vars) / 2, so 512 matches. Can you test how fast you can do the projection for 512 x 512 size matrices?

**Comment by omart-59** [comment]
Thanks for the reply. Since I consider complex hermitian matrices this makes sense. Projecting 3 (512 x 512) real matrices takes around 0.07 - 0.08 s; which is much closer to the time that the solver outputs. I guess this explains the main difference to what I initially measured.

**Comment by bodono** [comment]
Ok, looks like it's within a tolerance. SCS has to do other things like symmetrize the matrix first,  so it's probably about right.
