### ISSUE TITLE
Cannot install on Python 3.7

### ISSUE THREAD

**Issue by brains4math** [cvxgrp/scs#133]
Getting the following error:

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - scs -> python[version='2.7.*|3.5.*|3.6.*']

Your python: python=3.7

Is there a way to force it to install? Or is the only way to downgrade to python 3.6 ?

**Comment by bodono** [comment]
Where are you seeing that? SCS has no restriction on python version, in fact one of the tests on travis (that passes) tests against python [3.7.4](https://travis-ci.org/github/bodono/scs-python/jobs/613116680).

**Comment by brains4math** [comment]
Getting the error using pip install or conda install. The issue solved ( somehow ) after I ran 
conda config --add channels conda-forge
Only then conda install scs worked.
