### ISSUE TITLE
scs macosx py 3.7 wheel for 2.1.2 on pypi breaks cvxpy

### ISSUE THREAD

**Issue by mtreinish** [cvxgrp/scs#134]
In CI when the new version of scs is installed on osx 3.7 cvxpy can't find the solver. For example:

https://travis-ci.com/github/Qiskit/qiskit-ignis/jobs/302846114#L753

It looks like the sole wheel which was published for the new release: https://pypi.org/project/scs/#files does not work. Other python versions and operating systems which build the package from sdist did not fail in this manner.

Looking at past releases a single macos wheel was published for 2.7 not 3.7

**Comment by bodono** [comment]
Thanks, the wheel was indeed broken, I have just deleted the wheel from pypi so it should work now (from source).
