### ISSUE TITLE
cannot pip install scs 2.1.2

### ISSUE THREAD

**Issue by callegar** [cvxgrp/scs#135]
Seen on Linux.

`pip install scs` has started to fail. The error message does not really help me in tracing what is going on, though.

The only error I see in the output is
```
    /home/callegar/PythonEnvs/Py3.7-devel/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       17 | #warning "Using deprecated NumPy API, disable it with " \
          |  ^~~~~~~
```
There is a segmentation fault after this.

It is unclear to me how to deal with this, because the python wrappers do not seem to be maintained here. Yet, the `pypi` page points here.

**Comment by bodono** [comment]
Those warnings are not the source of the problem (they have always been there). Can you copy the entire trace here? I will try to reproduce in the mean time. The python wrapper is maintained [here](https://github.com/bodono/scs-python).

**Comment by bodono** [comment]
I just tested pip installing SCS on a clean conda install, python 3.7, debian (don't have access to ubuntu) and it installed and passed all tests.
