### ISSUE TITLE
Timelimit option

### ISSUE THREAD

**Issue by migarstka** [cvxgrp/scs#136]
It would be great to have the option to specify a limit on the time spent to find the solution. Something along the lines of:
- `optimizerMaxTime` in Mosek
- `time_limit` in OSQP

I am trying to solve a number of very large (sometimes badly scaled) problems and in some cases SCS won't converge. However, in those cases waiting for the iteration limit can take many hours.

**Comment by bodono** [comment]
Ok I can add this shortly.

**Comment by bodono** [comment]
This is in the 3.0.0 branch now.
