### ISSUE TITLE
Python installation fails on OS X Catalina 10.5.4

### ISSUE THREAD

**Issue by chase-dwelle** [cvxgrp/scs#138]
Originally posted this in the `cvxpy` repo: https://github.com/cvxgrp/cvxpy/issues/1024

I am trying to install `cvxpy` in a project and having issues with the `scs` dependency on OS X 10.15.4 (Catalina). I can install `scs` from source but not `scs-python`. I've confirmed that I can install on Ubuntu 18.04.4 and on another Mac using Catalina 10.5.3.

I am attempting to install with `poetry` but the installation from source instructions in the `scs-python` repo give the same result.

The issue is something related to the compilers in OS X, but not an issue I've come across before. I have installed/uninstalled XCode's command line tools as well as favored `gcc-8` and `gcc-9` compilers from Homebrew.

The error/warning log from the install is here:
https://gist.github.com/chase-dwelle/1aabbf07c39df6ab8844b515ed68c83f

**Comment by bodono** [comment]
I see many instances of `MacOSX10.14.sdk` in the logs and no instances of 10.15 (which is Catalina). The main problem seems to be that it's pulling in the wrong 'util.h'

``` 
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/util.h:64:
```

where it should be using the `scs/include/util.h` one. I've never seen that issue before, it might be something to do with one of your PATH  or PYTHONPATH variables. It might be that something in Catalina has changed how it is searching for the header files and I have to somehow be more specific.

I would suggest just using a virtual environment, like anaconda. This is good practice anyway. If you really need to install in the system python then we'll have to figure out why it's pulling in the wrong util.h.

**Comment by chase-dwelle** [comment]
Well that was simpler than I thought it would be. Removing the old Mojave SDK and reinstalling worked (the 10.15 SDK was also installed).
```bash
sudo rm -rf /Library/Developer/CommandLineTools/MacOSX10.14.sdk
```
Agreed on the virtual environments, `poetry` does use them for Python environments but this was an OS-level problem. I think the same thing is provided by `anaconda` unless I'm mistaken.

**Comment by vanshg** [comment]
Ran into a similar issue running Big Sur. Had to delete the Catalina SDK. `sudo rm -rf /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk`
