### ISSUE TITLE
Quiet NaN comparisons

### ISSUE THREAD

**Issue by adshieh** [cvxgrp/scs#139]
The `has_converged` function uses `<` comparisons of `res_pri`, `res_dual`, `rel_gap`, `res_unbdd`, and `res_infeas`, all of which can have NaN values. However, `<` comparisons with NaN values will raise `FE_INVALID` floating-point exceptions if they are enabled in the floating-point environment. On the other hand, [`isless`](https://en.cppreference.com/w/c/numeric/math/isless) comparisons with NaN values will always be quiet, regardless of the floating-point environment. Can we substitute the `<` comparisons in `has_converged` with `isless` comparisons?

**Comment by bodono** [comment]
OK, good point, will do.
