### ISSUE TITLE
write requirements at requirements of setup.py。and don't install by setup.py self

### ISSUE THREAD

**Issue by forbxy** [cvxgrp/scs#142]

**Comment by bodono** [comment]
Can you provide a little more detail? I'm not sure what the problem is here from just the description.

**Comment by forbxy** [comment]
scs download and install numpy by itself.
The normal way should be write it in setup.py( `setup(install_requires=requirements, ...)` )

**Comment by forbxy** [comment]
The first method always fails in China, because China has very narrow bandwidth for connecting to international networks, and the first method does not use cdn. I believe it will fail in many other countries
