### ISSUE TITLE
release scs-2.1.2

### ISSUE THREAD

**Issue by kalmarek** [cvxgrp/scs#144]
there is a tag, but release is missing
https://github.com/jump-dev/SCS.jl/issues/188

**Comment by bodono** [comment]
Ok, just released:

https://github.com/cvxgrp/scs/releases/tag/v2.1.2

**Comment by kalmarek** [comment]
thanks!

**Comment by kalmarek** [comment]
@bodono could you please release v2.1.4? I've seen that cvxpy is using this version, but tag/release are missing here
It is much easier to build the jll binary packages (to be used with SCS.jl) with the released versions

**Comment by bodono** [comment]
Just done.

**Comment by kalmarek** [comment]
thanks!
