### ISSUE TITLE
[openSUSE linux] libscsdir.a does not contain a non-empty .text section. The archive was not created with -ffat-lto-objects option

### ISSUE THREAD

**Issue by kevinsmia1939** [cvxgrp/scs#147]
Hello,
I'm trying to package scs to openSUSE Linux.

When I am trying to compile it, RPMLINT warn me about the error as seen below.

```
E: lto-no-text-in-archive (Badness: 10000) /usr/lib/libscsdir.a
E: lto-no-text-in-archive (Badness: 10000) /usr/lib/libscsindir.a
This archive does not contain a non-empty .text section.  The archive was not created with -ffat-lto-objects option.
```
I don't really understand this error myself, but some documentation here.
https://en.opensuse.org/openSUSE:LTO#LTO_enablement_in_openSUSE:Factory

The documentation suggest adding %global _lto_cflags %{?_lto_cflags} -ffat-lto-objects but openSUSE maintainer suggest that it should be fix upstream.
Here is some more documentation on LTO
https://gcc.gnu.org/onlinedocs/gccint/LTO-Overview.html

Here is a openSUSE package building log: https://build.opensuse.org/package/live_build_log/home:andythe_great/scs/openSUSE_Tumbleweed/x86_64

Thanks.

**Comment by bodono** [comment]
Hi Kevin, thanks for flagging these. I'm currently traveling but I will take a look when I get back next week. If you find anything else feel free to open more issues and I'll add them to my to-do list.

**Comment by kevinsmia1939** [comment]
> Hi Kevin, thanks for flagging these. I'm currently traveling but I will take a look when I get back next week. If you find anything else feel free to open more issues and I'll add them to my to-do list.

Hello,

I have ask RPMLINT dev and they explain here, quote,
https://github.com/rpm-software-management/rpmlint/issues/458

```
It is because of LTO compilation the openSUSE does.

If it is not compiled with this option then stuff gets optimized away and things tend to completely break.

This can't be generalized as all the static libraries need to have this argument passed in their cflags. Yet another policy tho tells you 'no static libraries' so at the moment from all the packages in Tumbleweed I see 50 that need this tweaking.

In theory it can be fixed in upstream as well, as it is not SUSE specific but rather LTO specific thingy, but if the upstream does not care about link time optimalization then the global is pretty decent solution.

Also if you happen to have some wording suggestion that would improve the understanding for you please feel free to propose it here and we will gladly update the message in rpmlint.
```

Anyway, I think I will just add the flag %global _lto_cflags %{?_lto_cflags} -ffat-lto-objects to my spec file, and that should be ok.
Thanks.
