### ISSUE TITLE
scs windows 32-bit and 64 -bit installation

### ISSUE THREAD

**Issue by bolcah** [cvxgrp/scs#15]
Hello.

I have been using cvx for almost 4 months, and I wanted to add the scs to the cvx solver list. I downdloaded the whole zip file of scs and copied the unzipped file into the cvx directory. I then copied cvx_scs into cvx shim folder and I ran the cvx_install_scs. I get the following error:
Error using mex (line 206)
Unable to complete successfully.
Error in compile_direct (line 24)
eval(cmd);
Error in make_scs (line 10)
compile_direct(flags);
Error in cvx_install_scs (line 2)
make_scs 

Please help

**Comment by aminghazanfari83** [comment]
Hello,

I am wanted to install SCS on matlab but I am getting the following error:


    mex:  ../linsys/direct/external/amd_order.c  not a normal file or does not exist.

Unable to complete successfully.

Error in compile_direct (line 17)
eval(cmd);

Error in make_scs (line 32)
compile_direct(flags, common_scs);
 

Could you please help me to solve this issue?

**Comment by bodono** [comment]
What platform are you on (windows 7, linux etc.)?

**Comment by aminghazanfari83** [comment]
Macbook pro OS X Yosemit

**Comment by bodono** [comment]
Works fine for me on my Macbook with El Capitan and Matlab R2014b, and on linux Matlab 2013a. I would make sure you path isn't getting messed up (type 'pathtool' at the matlab prompt), if that looks ok try restarting, and make sure when you type 'make_scs' to do it in the scs/matlab directory.

**Comment by aminghazanfari83** [comment]
I did check them and all arre fine, but still got the same error

**Comment by bodono** [comment]
Make sure you've pulled down the latest scs too.

**Comment by aminghazanfari83** [comment]
I still have same problem, could you please help me to solve this issue?

" mex:  ../linsys/direct/external/amd_order.c  not a normal file or does not exist.

Unable to complete successfully.

Error in compile_direct (line 17)
eval(cmd);

Error in make_scs (line 32)
compile_direct(flags, common_scs);"

**Comment by bodono** [comment]
Is that file actually missing?

**Comment by aminghazanfari83** [comment]
nope, the file is in there.

**Comment by bodono** [comment]
What directory are you running make_scs in? Can you edit the compile_direct file so that it uses `mex -v` (for verbose) and re-run, and paste the output here.

**Comment by aminghazanfari83** [comment]
I updated the file: mexopts.sh in matlab followed the answer provided in:
http://www.mathworks.com/matlabcentral/answers/103904-can-i-use-xcode-5-as-my-c-or-c-compiler-in-matlab-8-1-r2013a-or-matlab-8-2-r2013b 

I Replace all instances of 10.7 with 10.11 and then could use make_scs without any error. 

Thanks for your support :)

**Comment by bodono** [comment]
Great, happy it worked out
