### ISSUE TITLE
Add Cmake build system to scs

### ISSUE THREAD

**Issue by GiulioRomualdi** [cvxgrp/scs#151]
Dear maintainers, 

in the laboratory in which I work (https://dic.iit.it/), we would like to use `scs` for solving SDP. Our code is mainly developed using C++ and built with the CMake build system (for example https://github.com/robotology/robotology-superbuild).

In this issue, I would like to ask you if you're interested to add a Cmake build system in your project. This building system can live alongside the current `makefile` and can be seen as just an additional way to build `scs`. 
In theory, no additional `c` code is required and only the CMake machinery should be implemented. 

Thanks to this machinery it would be simpler to link `scs` to consumer libraries with
```cmake
target_link_libraries(my_library scs::scs)
```

If you are interested in this. I can handle the implementation of the new feature.

cc @traversaro @s-dafarra @prashanthr05

**Comment by GiulioRomualdi** [comment]
Here you can find a working CMake build system for `scs` https://github.com/dic-iit/scs-cmake-buildsystem

**Comment by bodono** [comment]
This looks great, thanks for implementing it! Is it better to be a standalone project or included in the main repo? If standalone is better I can add some links from the README to point to it. Otherwise I am happy to accept a PR to merge into the main repo. Let me know!

**Comment by h-vetinari** [comment]
Any update on this? 🙃

**Comment by GiulioRomualdi** [comment]
Hi @h-vetinari . I can open a PR in the next few days
