### ISSUE TITLE
An example to solve QP problems via SOCP in C?

### ISSUE THREAD

**Issue by fanxinping** [cvxgrp/scs#154]
I want to use SCS to solve quadratic program in C, but I find no example in the document.
Can you provide an example for solving quadratic program or second-order cone program in the document? I don't know how to convert my problem to struct `ScsData` and `ScsCone`.
Thanks!

**Comment by bodono** [comment]
Currently the main branch of SCS only supports QPs through turning them into SOCPs, as you mention, although in the `qp*` branches I'm working on supoprting QPs natively (current main dev branch is ` qp_b_c_normalized_with_data`). If you want to go down the SOCP route you can find an example [here](https://github.com/cvxgrp/scs/blob/master/test/random_socp_prob.c).

**Comment by fanxinping** [comment]
Hi Brendan,

Thanks for your reply. After a few days of code-debugging and online-searching, I was still not able to see how a QP was converted to an SOCP.

I in fact started coding in Julia (https://github.com/jump-dev/SCS.jl)  to solve a QP problem and now switched to use C/C++ due to other reasons and ran into difficulty in directly calling your C library. This is the original Julia function.

```Julia
function opt_solver(exp_r,cov_f)
    # exp_r is a nx1 column vector.
    # cov_f is a nxn square symmetric positive definite matrix.
    n = length(exp_r)
    x = Convex.Variable(n)
    x_lower = 0.0
    x_upper = 1
    ret  = dot(x,exp_r)
    risk = Convex.quadform(x,cov_f)
    qp_min = -ret+0.5*risk
    p = Convex.minimize(-ret+0.5*risk,
                  sum(x) == 1,
                  x_lower <= x,
                  x <= x_upper );
    Convex.solve!(p, () -> SCS.Optimizer(verbose=false),verbose=false);
    return x.value
end
```

I am wondering if you could provide reference(s) to paper/book-chapter(s) detailing the math on which your code is based to convert a QP problem to an SOCP one. It looks like there are many ways to formulate an SOCP problem and then convert a QP into an SOCP. I am not sure which formulation you have adopted in your code. Apologies for this kind of basic questions as I am a newbie to this field.

It'll be also great if you could provide a C example that solves a QP problem via your SCS library. The example you cited the last time solves a straightforward SOCP problem.

Many thanks,
Xinping

**Comment by angeris** [comment]
(For a higher level reference for how to convert QCQPs to SOCPs, see [here](https://people.eecs.berkeley.edu/~elghaoui/Teaching/EE227A/lecture6.pdf). This one is over the "rotated" second order cone, which can be written in terms of the standard second order cone. In particular, `(x, y, t)` is in the rotated second order cone, if, and only if, `‖(2x, y-t)‖ ≤ y+t`, which is an SOC constraint.)

**Comment by bodono** [comment]
Thanks @angeris. Another reference is 6.2 in the SCS [paper](https://arxiv.org/pdf/1312.3039.pdf) where we convert a QP to an SOCP manually. If your QP includes a term in the objective like `x' P x` then you'll need to factorize `P`, eg, if `P = L L'` then you can rewrite the objective as `||Lx||^2` which can be converted to an SOCP, this is what cvxpy and others do under the hood. The other alternative is to use the new native QP solving branch `qp_b_c_normalized_with_data` which not only supports QPs but is overall faster and more robust. If you want to try using that I can help you get set up and make sure it's working, since it would be useful for me to have a beta tester.

**Comment by fanxinping** [comment]
Thanks for your reply.
I read those reference but I don't know how to convert an SOCP problem to SCS' standard form. I used `Convex.jl` and Julia debugger to find how `Convex.jl` convert convex optimization problem in 'natural' form into cone form by coding some simple problem. I understand the way `Convex.jl` used when solve LP problem, but I am confused when solve the SOCP problem. Let me explain those using a simple QP problem.
I want to solve a QP problem:
![image](https://user-images.githubusercontent.com/23021820/106568036-af310c80-656d-11eb-9a31-ec68dcf878f5.png)
Then, covert it to SOCP form:
![image](https://user-images.githubusercontent.com/23021820/106568075-bd7f2880-656d-11eb-9172-4ffccca058ee.png)
When `Convex.jl` construct `ScsData` and `ScsCone`, and pass them to C API, I use debugger tool to view those related data.
![image](https://user-images.githubusercontent.com/23021820/106571059-ad694800-6571-11eb-80bc-a1beb05ac270.png)
This means, line 1 of A is linear equality constraints, line 2 of A is LP cone, line 3-6 and line 7-9 of A are second-order cone constraints. line 4-6 of A contain the data of sqrt(Q), because `Convex.jl` use sqrt to process Q instead of cholesky decomposition. 
I don't know how Eq(2) in fig became two second-order cone constraints and why A has a LP cone (this is no LP constraints in original problem).

Thanks

**Comment by bodono** [comment]
Your formulation in the second figure looks correct to me (though you don't need the `t` term) and you should be able to convert that to the canonical form that SCS expects `(A, b, c, cone)` with the addition of some extra variable, ie:
```
min c'x
s.t  Ax + s = b
      s \in cone
```
It could very well be the case that Conjex.jl is creating a sub-optimal canonicalization of the problem, I don't see what the LP cone (the second row of A) is doing, it looks to me like you could just remove it. Typically the smaller and closer to the original problem the better when converting problems into canonical format (though not always).

**Comment by fanxinping** [comment]
Dear Brendan, 

After exhaustive online searching/reading, I couldn't find the details in converting my Eq(2) to "the canonical form that SCS expects (A, b, c, cone) with the addition of some extra variable"?

```
min c'x
s.t  Ax + s = b
      s \in cone
```

Is it possible that you can jot it down in a napkin and upload a photo? :)

Thanks,

**Comment by bodono** [comment]
Ok, it's attached.
![PXL_20210204_210646698](https://user-images.githubusercontent.com/555071/106955385-1943e000-672d-11eb-83cb-58240266de67.jpg)

**Comment by fanxinping** [comment]
Thank you very much.
