### ISSUE TITLE
How to hidden the error: WARN: A->p (column pointers) not strictly increasing, column X empty?

### ISSUE THREAD

**Issue by segeral** [cvxgrp/scs#196]
**Problem Background**
I'm currently working on some problems with quantum computing, and I need to solve **SDP** involving **complex matrices**. I also browsed related issues before(https://github.com/cvxpy/cvxpy/issues/481), but found that his issue is not quite the same as mine.

My program **does not fail**, and the results are **as expected**. But the annoying **WARN** always pops up when the program is running.

**Output**
```
WARN: A->p (column pointers) not strictly increasing, column 3 empty
WARN: A->p (column pointers) not strictly increasing, column 6 empty
WARN: A->p (column pointers) not strictly increasing, column 10 empty
WARN: A->p (column pointers) not strictly increasing, column 13 empty
WARN: A->p (column pointers) not strictly increasing, column 17 empty
WARN: A->p (column pointers) not strictly increasing, column 20 empty
WARN: A->p (column pointers) not strictly increasing, column 24 empty
WARN: A->p (column pointers) not strictly increasing, column 27 empty
Unsteerable
```
These WARNs always pop up every time I run the program, and every time the WARN pops up is **exactly the same**. 

So, how can I hide these errors? Because they affect the aesthetics and prevent me from seeing the results.

**Version**
 - OS: Windows 11
 - CVXPY Version: 1.1.18
 - Python Version: 3.9.7

Also, my IDE is Visual Studio Code and using anaconda environment.

**Comment by bodono** [comment]
I can put these warnings inside the `verbose` setting, but it does look like cvxpy is generating a problem where some of the variables aren't appearing in the constraints, only in the objective, which means the problem is likely ill-posed.

Can you post the output that SCS prints out when you pass `verbose=True` into the solve call?

**Comment by rbassett3** [comment]
@bodono I don't know where OP went but I'm having this issue as well. Everything is solving correctly, which I confirmed by deriving the dual problem by hand. Here's the output with `verbose=True`.


```
----------------------------------------------------------------------------
	SCS v2.1.2 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 15550
eps = 1.00e-04, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 20300, constraints m = 25450
Cones:	sd vars: 25150, sd blks: 2
	exp vars: 300, dual exp vars: 0
Setup time: 1.12e-02s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 1.68e+01  2.42e+00  1.00e+00 -1.88e+03  1.43e+03  7.92e-13  8.54e-03 
    80| 3.61e-07  4.29e-05  2.21e-08  9.96e+01  9.96e+01  2.05e-13  8.74e-01 
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 8.74e-01s
	Lin-sys: nnz in L factor: 61300, avg solve time: 2.62e-04s
	Cones: avg projection time: 8.03e-03s
	Acceleration: avg step time: 1.85e-03s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 1.1567e-09, dist(y, K*) = 1.6150e-09, s'y/|s||y| = -2.6321e-12
primal res: |Ax + s - b|_2 / (1 + |b|_2) = 3.6054e-07
dual res:   |A'y + c|_2 / (1 + |c|_2) = 4.2853e-05
rel gap:    |c'x + b'y| / (1 + |c'x| + |b'y|) = 2.2119e-08
----------------------------------------------------------------------------
c'x = 99.5768, -b'y = 99.5768
============================================================================
1.214021921157837
```

**Comment by segeral** [comment]
@rbassett3 This problem can be solved using the MOSEK solver.

**Comment by bodono** [comment]
I just disabled this check, so will be gone as soon as the branch merges with master.
