### ISSUE TITLE
How to choose start point for warm start?

### ISSUE THREAD

**Issue by ZedongPeng** [cvxgrp/scs#209]
## Specifications
- OS: CentOS
- SCS Version: 3.2.0
- Compiler:

## Description

I am playing with the `warm_start` in SCS. I find that SCS will do a check for the provided start point if `warm_start=True`. 
If the start point is not provided properly, SCS will report `Error parsing warm-start input`.

For first-order method, a good start point can help a lot. I am now trying to find a good heuristic or ML method to generate a good start point for my problem. I know there are a lot of theory behind the primal/dual problem and solution.

Therefore, **I am really curious about the logic behind the start point check in SCS.** Are you checking the feasibility of primal/dual problem if the initial primal/dual solutions are provided? 
I would appreciate if you could give inspirations.

## How to reproduce
Ideally a minimal snippet of code that reproduces the problem if possible.
The following problem is the Basic QP provided in the online doc. Its optimal primal solution is `[ 0.3 -0.7]` and its optimal dual solution is `[2.7 2.1 0. ]`. If I set the initial primal solution to `[0.3, -0.7]` and initial dual solution to `[1, 1, 1]`. SCS will report `Error parsing warm-start input`.

```
import scipy
import scs
import numpy as np

# Set up the problem data
P = scipy.sparse.csc_matrix([[3.0, -1.0], [-1.0, 2.0]])
A = scipy.sparse.csc_matrix([[-1.0, 1.0], [1.0, 0.0], [0.0, 1.0]])
b = np.array([-1, 0.3, -0.5])
c = np.array([-1.0, -1.0])
print(A.shape)
# Populate dicts with data to pass into SCS
data = dict(P=P, A=A, b=b, c=c)
cone = dict(z=1, l=2)

# Solve!
solver = scs.SCS(data, 
                cone, 
                eps_abs=1e-9, 
                eps_rel=1e-9)
# sol = solver.solve()
sol = solver.solve(warm_start=True,
                  x=np.array([0.3, -0.7]),
                  y=np.array([1, 1, 1]),
                  s=None)

print(f"SCS took {sol['info']['iter']} iters")
print("Optimal solution vector x*:")
print(sol["x"])

print("Optimal dual vector y*:")
print(sol["y"])
```

## Output
`Error parsing warm-start input`

**Comment by bodono** [comment]
Happy to discuss how the warm-starts work, but first - that code seems to run fine for me.
```
=> python tmp.py

(3, 2)
------------------------------------------------------------------
	       SCS v3.2.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 2, constraints m: 3
cones: 	  z: primal zero / dual free vars: 1
	  l: linear vars: 2
settings: eps_abs: 1.0e-09, eps_rel: 1.0e-09, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct
	  nnz(A): 4, nnz(P): 3
Error parsing warm-start input
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.21e+00  2.70e+00  1.70e-01  9.44e-01  1.00e-01  1.36e-04
    75| 4.19e-10  8.11e-10  1.10e-09  1.24e+00  1.00e-01  7.55e-04
------------------------------------------------------------------
status:  solved
timings: total: 1.25e-03s = setup: 4.82e-04s + solve: 7.68e-04s
	 lin-sys: 2.08e-05s, cones: 7.08e-06s, accel: 3.82e-04s
------------------------------------------------------------------
objective = 1.235000
------------------------------------------------------------------
SCS took 75 iters
Optimal solution vector x*:
[ 0.3 -0.7]
Optimal dual vector y*:
[2.7 2.1 0. ]

```

**Comment by ZedongPeng** [comment]
My mistake for not describing this clearly. Even if the start point is not provided properly, SCS will not fail. Nothing will show up if you run the code in the **terminal**. However, if you run the Python script in **JupyterLab**, there is a **note** or a **warning**. I also tried solving the model without `warm_start`. It still took 75 iterations to converge. Without no more information, I guess the `warm_start` might not succeed. 

<img width="548" alt="image" src="https://user-images.githubusercontent.com/15854830/154981995-13de47a9-46b1-4a13-a316-734665d6b86f.png">

**Comment by bodono** [comment]
Ohhh, I see what's happening. The problem is that since you don't set the `s` warm-start it is unable to parse it out. All this means is that it will use the other warm-starts (`x`, `y`) correctly and just set `s` to zero.  The real problem is that error message is bad, I can fix that, but your warm starts are getting parsed correctly. If you supply a good warm-start, then you will see that it takes less than 75 iterations to converge.

**Comment by bodono** [comment]
This PR: https://github.com/bodono/scs-python/pull/60 fixes it.

**Comment by ZedongPeng** [comment]
Hi @bodono . Thanks a lot for your reply. I am still puzzled about the parsing error reported by SCS. You said `Error parsing warm-start input` is reported since `s` is not provided. So I give it a test as follows. 

I still only provide `x` and `y` for `warm_start` and but the value of `x` and `y` is optimal. In this case, there is no `Error parsing warm-start input`. 
![image](https://user-images.githubusercontent.com/15854830/155052959-c1ca92cd-3518-48ff-9e42-44900bd4d079.png)

To make it more general, I set initial `x` to `[0.2, -1]` and initial `y` to `[2.1, 1.1, 1]`. The output is as follows and no parsing error is reported. It looks like that the parsing error doesn't result from the missing of `s`. I am really curious about the logic behind the `warm_start` check. Looking forward to your reply. 
![image](https://user-images.githubusercontent.com/15854830/155053298-30c67583-a07e-4f6a-a531-d3a67a29f137.png)

**Comment by ZedongPeng** [comment]
> Hi @bodono . Thanks a lot for your reply. I am still puzzled about the parsing error reported by SCS. You said `Error parsing warm-start input` is reported since `s` is not provided. So I give it a test as follows.
> 
> I still only provide `x` and `y` for `warm_start` and but the value of `x` and `y` is optimal. In this case, there is no `Error parsing warm-start input`. ![image](https://user-images.githubusercontent.com/15854830/155052959-c1ca92cd-3518-48ff-9e42-44900bd4d079.png)
> 
> To make it more general, I set initial `x` to `[0.2, -1]` and initial `y` to `[2.1, 1.1, 1]`. The output is as follows and no parsing error is reported. It looks like that the parsing error doesn't result from the missing of `s`. I am really curious about the logic behind the `warm_start` check. Looking forward to your reply. ![image](https://user-images.githubusercontent.com/15854830/155053298-30c67583-a07e-4f6a-a531-d3a67a29f137.png)

Hi @bodono . I saw this issue has been resolved by PR #60 . I just have one more question as I quoted here. I would really appreciate if you could help me to figure it out.

**Comment by bodono** [comment]
Hmmm, in that case my guess is that `y=np.array([1, 1, 1])` is not getting parsed correctly because it is integers rather than floats, try setting `y=np.array([1., 1., 1.])`.

**Comment by ZedongPeng** [comment]
Hi @bodono . Thanks a lot for your reply. I just tested `y=np.array([1., 1., 1.])`. It is parsed correctly and takes 100 iterations to converge, different from 75 iterations when without `warm_start`. I think this issue is resolved. 
Thanks a lot for your help.
