### ISSUE TITLE
Function call in MAX and MIN macro

### ISSUE THREAD

**Issue by Gwzwpxz** [cvxgrp/scs#231]
In ```src/normalize.c[41]``` there's function call within the MAX(a, b) macro

> sigma = MAX(SCS(norm_inf)(c, scal->n), SCS(norm_inf)(b, scal->m));

where ```SCS(norm_inf)(b, scal->m)``` seems executed four times per call after expansion.

Similar case happens within MIN(a, b) from ```src/scs.c[373, 378]``` 

>   tol = CG_TOL_FACTOR * MIN(tol, CG_NORM(warm_start, w->d->n) / POWF((scs_float)iter + 1, CG_RATE));
> tol = MIN(CG_NORM(w->r_normalized->ax_s_btau, w->d->m), CG_NORM(w->r_normalized->px_aty_ctau, w->d->n));

**Comment by bodono** [comment]
Yes, you're absolutely right, thank you for pointing this out @Gwzwpxz !

I will fix it asap.

**Comment by bodono** [comment]
After fixing the issue when I run the direct solver test suite the total number of l-infinity norm calls drops from `52678` down to `36835`, a nice saving!

**Comment by Gwzwpxz** [comment]
Quite nice to hear that!  : )
