### ISSUE TITLE
Overriding BLAS/LAPACK with environment variables [python]

### ISSUE THREAD

**Issue by rmcgibbo** [cvxgrp/scs#33]
As mentioned in #12, on windows one really wants to link against a static `libblas.a` (actually `libblas.lib`) since there are no system libraries. In situations like this, it would be convenient to be able to configure the scs blas linkage independently of numpy, for example by simply loading include path, library path and library names from environment variables or --command-line-flags, instead of looking to `numpy.distutils`.

**Comment by rmcgibbo** [comment]
I'm currently maintaining a patch against `setup.py` that simply overrides `numpy.distutils.system_info.get_info` with
```
def get_info(x):
    import os
    return {
        'include_dirs': [os.environ.get('LAPACK_INCLUDE_PATH', '')],
        'library_dirs': [os.environ.get('LAPACK_LIB_PATH', '')],
        'libraries': os.environ.get('LAPACK_LIBS', '').split(),
    }
```
But something similar could be incorporated into the script, only activating if the three environment variables were actually available or something.

**Comment by bodono** [comment]
That's a good idea. Is there any standard environment variable names for those locations that you know of?

**Comment by rmcgibbo** [comment]
No, I'm not aware of any standard names. Probably if [this stuff](https://github.com/cvxgrp/scs/blob/master/python/setup.py#L94-L97) gets printed, it could just mention the environment variable it knows about.

**Comment by tkelman** [comment]
Matlab uses `BLAS_VERSION` and `LAPACK_VERSION` to let you switch to a different implementation, though it's not very well-documented.

**Comment by rmcgibbo** [comment]
To be able to provide the same information which is currently gleaned from
numpy.distutils' `get_info`, the include directories, library directories,
and the names of the libraries themselves need to be communicated
separately, I think.

**Comment by tkelman** [comment]
You shouldn't really need an include path for blas or lapack, since the signatures are all completely standard and well-documented.

**Comment by rmcgibbo** [comment]
Yeah, that's true. The `include`s are basically superfluous.

**Comment by bodono** [comment]
I just added this functionality to the v1.1.0 branch, the environment variables are:
BLAS_LAPACK_LIB_PATHS
BLAS_LAPACK_LIBS
