### ISSUE TITLE
scs using in C

### ISSUE THREAD

**Issue by LoweDavince** [cvxgrp/scs#37]
Hi,
When using scs in C examples demo.c associated with data "demo_data".Compiling is OK,but I got the "Error reading in data, aborting." Whats wrong??

Thanks~
LD

**Comment by bodono** [comment]
Thanks for pointing this out. The data file it's reading in has been corrupted somehow. Until I fix it you can test scs by running out/demo_SOCP_indirect or out/demo_SOCP_direct, which generate and solve random SOCPs.
