### ISSUE TITLE
Memory error in SCS

### ISSUE THREAD

**Issue by SteveDiamond** [cvxgrp/scs#41]
When I test cvxpy with SCS on Ubuntu, I get memory errors. You can see an example here:

https://travis-ci.org/cvxgrp/cvxpy/jobs/65967866

If I run all the tests without SCS, there are no memory errors (nor were there with the old SCS). So I strongly suspect the issue is in SCS.

Here's a terminal.com snapshot I've been using to replicate the memory error:

https://www.terminal.com/snapshot/e25a3905cd195111dfd8fdf92ecda788a2226ebacf3930a518c4fe604ee36631

**Comment by bodono** [comment]
What do you mean by memory error? I can't tell what's happening there. Is it a leak, or accessing unallocated memory or something else?

**Comment by SteveDiamond** [comment]
I don't really know. I've never seen a problem like this before. Python says there was a ``double free or corruption``, so my guess is that some array is being freed in SCS that shouldn't have been.

The problem only happens when I run nosetests, which evaluates many functions in parallel. I can't replicate it in the python shell running functions serially, so I wasn't able to get a clearer debugging message about the nature of the memory error.

You can replicate/investigate the problem by going to this snapshot

https://www.terminal.com/snapshot/ebc22d6220b84351c0bbe45e0a3428fbbd8815117127d860e948b369ebc335e4

and running the following:
```
nosetests cvxpy/tests/test_scs.py
```

**Comment by bodono** [comment]
Looks like it's got something to do with the warm-start vectors that can be passed in. Still working on it.

**Comment by SteveDiamond** [comment]
That makes a lot of sense. It also happens when I run
```
nosetests cvxpy/performance_tests/test_warmstart.py
```

**Comment by bodono** [comment]
Ok, I've figured it out, it's that I'm free-ing the warm-starts twice basically. I just looked at that code again and there are a couple of weird things that I would like to fix in one go. I'll push a new version tomorrow, it's getting late here...

**Comment by SteveDiamond** [comment]
That's awesome you figured it out! No rush, push when you're ready.

**Comment by bodono** [comment]
Just pushed a fix.

**Comment by SteveDiamond** [comment]
Great! It works for me now. Can you tag a new version and upload it to pypi?
