### ISSUE TITLE
Callling SCS from C

### ISSUE THREAD

**Issue by arnres** [cvxgrp/scs#43]
I'm coding in C. I have all my data organized in the form that SCS needs to take but when I call the SCS functions, I get

ERROR: A->p (column pointers) decreasing
invalid linear system input data
ERROR: Validation returned failure
ERROR: NULL input

I've seen a github issue with this error here. https://github.com/JuliaOpt/Convex.jl/issues/88. I can provide more information if needed as well.

Thanks!

**Comment by bodono** [comment]
That error means that the column pointers are decreasing in your data matrix A. Here is an example of a valid ccs matrix:

http://netlib.org/linalg/html_templates/node92

As you can see the column pointers should be non-decreasing, since the col_ptr stores the index of the elements in of the values array which start a column of A.
Does that help?

**Comment by arnres** [comment]
Thank you for the help. I fixed the column pointer issue. Now the error is 

eps tolerance must be positive
ERROR: Validation returned failure
ERROR: NULL input

I set eps to .001 as suggested on the scs page and tried increasing the value but still see this error.

Thanks!

**Comment by bodono** [comment]
Hmm, that's strange. Do you have a small example I can test with?

**Comment by arnres** [comment]
Thank you. My code happens to be not too small as I first started out with complex data and had to do a lot of reorganization to get it in the form that SCS would take. I followed the procedure in MATLAB and was successful in calling SCS. Therefore, I know that my data is in the correct form. However, since I'm getting this error in C, I suspect it is because of the way I populate the structs. Can I send you my C code for testing?

Also, in this struct

    /* struct containing problem data */
    struct SCS_PROBLEM_DATA {
        /* these cannot change for multiple runs for the same call to scs_init */
        scs_int m, n;       /* A has m rows, n cols */
        AMatrix * A;        /* A is supplied in data format specified by linsys solver */

        /* these can change for multiple runs for the same call to scs_init */
        scs_float * b, *c;  /* dense arrays for b (size m), c (size n) */

        Settings * stgs;    /* contains solver settings specified by user */
    };

c is an array that repeats [1 0 0], right? I don't understand why it is defined as a float and not an int.

Thanks!

**Comment by bodono** [comment]
Sure, you can send me your C code and I can take a look.

Why would `c` be `[1,0,0]` repeating? Is that just your problem formulation? Here `c` is the constant vector in the primal cone program objective function, ie, we minimize `c'*x` where `x` is a primal variable.

**Comment by arnres** [comment]
Thank you very much for your guidance. I emailed the code to bodonoghue85@gmail.com.

Thanks!
