### ISSUE TITLE
SCS with GPU support

### ISSUE THREAD

**Issue by btabibian** [cvxgrp/scs#49]
I noticed there is a GPU support for SCS now in master. I tried it but failed to install.

After running `make purge && make && make gpu` and compiling gpu component I run setup.py with `GPU=True`. However, I get following error:

```
/usr/bin/ld: cannot find -lscsgpu
/usr/bin/ld: skipping incompatible /usr/local/cuda/lib/libcudart.so when searching for -lcudart
/usr/bin/ld: cannot find -lcudart
/usr/bin/ld: skipping incompatible /usr/local/cuda/lib/libcublas.so when searching for -lcublas
/usr/bin/ld: cannot find -lcublas
/usr/bin/ld: skipping incompatible /usr/local/cuda/lib/libcusparse.so when searching for -lcusparse
/usr/bin/ld: cannot find -lcusparse
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lscsgpu
/usr/bin/ld: skipping incompatible /usr/local/cuda/lib/libcudart.so when searching for -lcudart
/usr/bin/ld: cannot find -lcudart
/usr/bin/ld: skipping incompatible /usr/local/cuda/lib/libcublas.so when searching for -lcublas
/usr/bin/ld: cannot find -lcublas
/usr/bin/ld: skipping incompatible /usr/local/cuda/lib/libcusparse.so when searching for -lcusparse
/usr/bin/ld: cannot find -lcusparse
collect2: error: ld returned 1 exit status
```

Any suggestions why this may happen?

**Comment by bodono** [comment]
It looks like it's complaining about incompatible versions of the CUDA libs. I would suggest installing the latest version from https://developer.nvidia.com/cuda-downloads, and making sure you get the right version for your architecture. Let me know how that goes.

**Comment by btabibian** [comment]
@bodono Thanks for your reply, what is the minimum requirements for running GPU version?

**Comment by bodono** [comment]
You need to have an NVidia CUDA-capable GPU, with the CUDA toolkit installed. Here is the list of CUDA capable GPUs (basically anything from NVidia for the last several years):

https://developer.nvidia.com/cuda-gpus

This question deals with the same incompatible library problem, which is what lead me to believe you might be using the wrong architecture for your system:

http://stackoverflow.com/questions/17080280/skipping-incompatible-libcudart-so-when-searching-for-lcudart

What operating system are you using? GPU support in python is fully supported yet, but it can work with a bit of work.

**Comment by btabibian** [comment]
@bodono I am working on Ubuntu with several GPUs and nvcc 6.0. I have other codes that work fine. I will look into the stackoverflow entry, see if I can find out the problem.

**Comment by bodono** [comment]
On linux there are a couple of small changes you need to make:
1) Make sure nvcc is in the path (it probably is for you already, but just to make sure). e.g.
```
export PATH=/Developer/NVIDIA/CUDA-7.5/bin/:$PATH
```
(or wherever it is)
2) Make sure that the LD_LIBRARY_PATH points to wherever you compiled libscsgpu.so, so something like
```
export LD_LIBRARY_PATH=/XXX/scs/out:$LD_LIBRARY_PATH
```
3) Edit python/setup.py line 75 to look like
```
library_dirs=library_dirs + ['/usr/local/cuda/lib64', '/usr/local/lib64'],
```
(or wherever the libraries are installed to)

That *might* work. I'm hoping to make the process much easier, I just haven't gotten around to it yet.

**Comment by btabibian** [comment]
@bodono I will try that, no worries about the issues. It is already awesome to see the work in this direction. cheers!

I will try this and let you know if it worked.

**Comment by btabibian** [comment]
@bodono Almost all of the issues went away except it still does not find libscsgpu.so(which is present in scs/out). I made the change to LD_LIBRARY_PATH but `python setup.py install` is not able to pick it up. 

I am also using this inside a virtual environment. Do you have any guess as what might be the problem?

**Comment by btabibian** [comment]
@bodono I managed to compile it. The problem was that 

``export LD_LIBRARY_PATH=/XXX/scs/out:$LD_LIBRARY_PATH``

should be 

``LIBRARY_PATH=/XXX/scs/out:$LIBRARY_PATH``

**Comment by bodono** [comment]
Great, to test it you can run the script in `examples/python/solveRandomConeProbGpu.py`.

**Comment by bodono** [comment]
The random problem that script was generating was quite large, I just pushed a fix to make it generate a small one for testing. You can obviously change this yourself too if you want.

**Comment by btabibian** [comment]
Thanks for the pointer, in fact I was not passing GPU argument to the program. It is working like :)

Do you have any general idea of how much speed up one can gain by using GPU version?

**Comment by bodono** [comment]
It can be pretty significant, but only for medium to large size problems, since for small problems the overhead of transferring the data to the gpu dominates. It can easily be >10x speedup vs single threaded CPU (which the SCS in python is by default, unless you manually enable openmp support), and about 3x vs multiple threads when I tested against 32 cores.

Since it's working I'm going to close the issue. Feel free to re-open if you're still having problems.

**Comment by a-cvision** [comment]
Hi
I wanted to know if there is already a MATLAB interface with GPU support for SOCP problems. I am interested in large scale problems (about 5 hundred thousand variables or more).
I have tried the mex'ed version with openmp and it appears to be already faster or similar to Mosek.

**Comment by bodono** [comment]
Unfortunately right now we don't have a GPU mex interface. I'll put it on the TODO list and try and put it in when I get a chance. One caveat - a 500k variable problem might not fit on your GPU.

**Comment by a-cvision** [comment]
Yes, it might be too large for most GPUs. I didn't foresee that side of the problem. Anyways thanks for the quick reply!
