### ISSUE TITLE
OpenMP with SCS

### ISSUE THREAD

**Issue by btabibian** [cvxgrp/scs#51]
Hi again,

Sorry for making too many requests! 

Is there a way to check if SCS is correctly configured to run on OpenMP? Of course I can check through number of processes and CPU consumption but I was wondering if there is anything inside that could show how many threads are used.

**Comment by bodono** [comment]
In python you can change [this line in setup.py]( https://github.com/cvxgrp/scs/blob/fed3ac9419707166bc1ec123a14c58c3680c0740/python/setup.py#L102) to read `USE_OPENMP = True` to activate openmp. Your compiler has to support openmp pragmas, which gcc and more recent versions of clang do. To see if you're actually using threads you can just use the linux `top` or `htop` command.  Use 'export OMP_NUM_THREADS=32' to control num of threads (e.g. 32).
