### ISSUE TITLE
SCS taking hours to set up

### ISSUE THREAD

**Issue by btabibian** [cvxgrp/scs#52]
I have a an optimization program with 11M data points taking over 20hours to run the first iteration. smaller datasets with 7M data points run in significantly shorter time. Is there anyway I could investigate why it takes such long time?

Following is the problem statement printed by SCS:

Lin-sys: sparse-direct, nnz in A = 326795355
eps = 1.00e-03, alpha = 1.50, max_iters = 200, normalize = 1, scale = 1.00
Variables n = 53115585, constraints m = 117868881
Cones:        primal zero / dual free vars: 1
             linear vars: 39616055
             exp vars: 78252825, dual exp vars: 0

**Comment by bodono** [comment]
I would recommend not using the direct version of SCS for large problems, the factorization step is O(n^3) and subsequent steps are O(n^2). Use the indirect version (or GPU version) which only uses matrix multiplies which are O(n^2) per iteration. In python pass in 'use_indirect=True' to SCS or CVXPY.

**Comment by btabibian** [comment]
Thanks for the info. Is there anywhere that I could find the list of arguments? and some description of the algorithm?

**Comment by bodono** [comment]
Did that solve the problem for you?

[This section in the README](https://github.com/cvxgrp/scs#using-scs-in-python) has a list of all the arguments for the python API (actually it's missing the gpu argument because it's new).

[Our paper](http://www.stanford.edu/~boyd/papers/scs.html) gives a full description of the algorithm.

**Comment by btabibian** [comment]
Thanks for getting back to me.

The new run with indirect command is taking less memory, however after 6 hours it has still not finished a single iteration. 

```
INFO:root:Lin-sys: sparse-indirect, nnz in A = 326795355, CG tol ~ 1/iter^(2.00)
INFO:root:eps = 1.00e-03, alpha = 1.50, max_iters = 200, normalize = 1, scale = 1.00
INFO:root:Variables n = 53115585, constraints m = 117868881
INFO:root:Cones:        primal zero / dual free vars: 1
INFO:root:      linear vars: 39616055
INFO:root:      exp vars: 78252825, dual exp vars: 0
INFO:root:Setup time: 9.28e+01s
```

**Comment by bodono** [comment]
Are you compiling with openmp support? This distributes the matrix multiply and the exponential cone projections across multiple threads which should make it faster.
```
python setup.py install --scs --openmp
```

You can also compile with a more verbose output to make sure it's actually progressing (it will tell you more information about what step it's in etc.)
```
python setup.py install --scs --openmp --extraverbose
```
warning - this will dump a lot of information.

**Comment by btabibian** [comment]
I did pass --extraverbose to setup.py, do I need to add anything on python interface? I am not seeing anything out of usual outputs.

**Comment by bodono** [comment]
You shouldn't need to do anything else. Did it install correctly?

**Comment by btabibian** [comment]
Yes, but let me reinstall again and get back to you again. There might be something I missed.

**Comment by bodono** [comment]
What version does SCS say it is at the top? This requires at least 1.2.0.

**Comment by btabibian** [comment]
I am working on master branch, 1.2.1.

**Comment by btabibian** [comment]
So I reinstalled and got the OpenMP working, however I didn't get extraverbose working yet.

Thanks,

**Comment by bodono** [comment]
It's good that openMP is working at least :). (Make sure you can see the CPU go above 100% in when using `top`). To try again with extraverbose do these steps:

```
cd scs/python
rm -rf build/
python setup.py install --scs --openmp --extraverbose
cd ../examples/python
python solveRandomConeProb.py 
```

You might need `sudo` for a couple of those steps, and make sure the compilation completes successfully.

**Comment by btabibian** [comment]
I will try that. In the mean time, is there a batch version indirect implementation? 

From what I learned in-direct method implements gradient based method and having a batch implementation may help a lot.

**Comment by bodono** [comment]
The indirect method uses conjugate gradient in the linear system solve, it uses a form of early termination to save on computation which the algorithm is (provably) robust to. The direct method solves the linear system via LDL factorize-and-solve. In my experiments they take roughly the same amount of iterations to solve a problem, the indirect method is faster for larger problems.

**Comment by btabibian** [comment]
Hi bodono,

The problem is solved, thanks for your input.

**Comment by prateeky2806** [comment]
Hello @btabibian 
I am also trying to solve a large problem, can you please elaborate on what finally worked for you and how much faster it was?

**Comment by bodono** [comment]
Are you using the direct solver? Switching to the indirect solver might be faster for large problems.
