### ISSUE TITLE
Converting SOCP problem to SCS's standard form

### ISSUE THREAD

**Issue by taogao** [cvxgrp/scs#54]
Hi,
SOCP is new to me. I'm learning convex optimization by following the Boyd & Vandenberghe (2010) Book. I'm very excited to find SCS and want to use to solve problems listed in that book. 
However, it is not quite clear to me how to convert a SOCP problem into the standard form of SCS. In Chapter 4 of Boyd&Vandenberghe's book, Page 156, SOCP is defined with both equality and inequality form.  It is not clear how to use SCS to solve it. 

I have read the paper introducing SCS. However, converting to the standard form is skipped (I guess it is obvious to experts in this field).

I also read the python example of minimizing L-1 norm. But setting up the input matrices looks like magic to me. 

So, I'm wondering whether anyone can point me to some papers/tutorials about how to convert SOCP problems to the standard from of SCS. It will be great if the authors can add a few examples, solving problems listed in Boyd &. Vandenberghe (2010). I think it will help many beginners a lot. 

Thanks very much!

Tao

**Comment by bodono** [comment]
There are actually software packages that automate the process of converting a convex optimization problem in 'natural' form into cone form for you, that work with SCS out of the box, e.g. cvxpy (python), cvx (matlab), Convex.jl (julia), among others.

If you want to learn how they do it, then the original cvx paper is probably a good place to start: http://stanford.edu/~boyd/papers/pdf/graph_dcp.pdf

**Comment by dbmptr** [comment]
Hi,
What to do if the project is being implemented in c for performance reasons? How to do the conversion then?
It would be really helpful to have a small example in the test directory that shows how to convert from 
||A_ix - b_i|| <= C_ix - d_i 
to 
Ax + s = b
s \in K .

Even after going through the graph_dcp document, I am still not sure how this conversion is done.

**Comment by bodono** [comment]
I think this book should help: https://web.stanford.edu/~boyd/cvxbook/
