### ISSUE TITLE
make_scs fails

### ISSUE THREAD

**Issue by hosseinghafarian** [cvxgrp/scs#57]
when I try to run make scs in a new computer, It fails, even when mex -setup works fine. It gives me the following messages: 

Building with 'Microsoft Visual C++ 2015 (C)'.
Error using mex
   Creating library E:\Ghafarian\scs-master\matlab\scs_direct.lib and object E:\Ghafarian\scs-master\matlab\scs_direct.exp
common.obj : error LNK2001: unresolved external symbol _mxMalloc
scs_mex.obj : error LNK2001: unresolved external symbol _mxMalloc
private.obj : error LNK2001: unresolved external symbol _mxMalloc
amd_global.obj : error LNK2001: unresolved external symbol _mxMalloc
cones.obj : error LNK2001: unresolved external symbol _mxMalloc
cs.obj : error LNK2001: unresolved external symbol _mxMalloc
scs.obj : error LNK2001: unresolved external symbol _mxMalloc
common.obj : error LNK2001: unresolved external symbol _mxCalloc
scs_mex.obj : error LNK2001: unresolved external symbol _mxCalloc
private.obj : error LNK2001: unresolved external symbol _mxCalloc
amd_global.obj : error LNK2001: unresolved external symbol _mxCalloc
cones.obj : error LNK2001: unresolved external symbol _mxCalloc
cs.obj : error LNK2001: unresolved external symbol _mxCalloc
scs.obj : error LNK2001: unresolved external symbol _mxCalloc
scs.obj : error LNK2001: unresolved external symbol _mxFree
common.obj : error LNK2001: unresolved external symbol _mxFree
scs_mex.obj : error LNK2001: unresolved external symbol _mxFree
private.obj : error LNK2001: unresolved external symbol _mxFree
amd_global.obj : error LNK2001: unresolved external symbol _mxFree
cones.obj : error LNK2001: unresolved external symbol _mxFree
cs.obj : error LNK2001: unresolved external symbol _mxFree
util.obj : error LNK2001: unresolved external symbol _mxFree
amd_global.obj : error LNK2001: unresolved external symbol _mxRealloc
common.obj : error LNK2019: unresolved external symbol _mexPrintf referenced in function _freeAMatrix
scs_mex.obj : error LNK2001: unresolved external symbol _mexPrintf
ldl.obj : error LNK2001: unresolved external symbol _mexPrintf
cones.obj : error LNK2001: unresolved external symbol _mexPrintf
util.obj : error LNK2001: unresolved external symbol _mexPrintf
scs.obj : error LNK2001: unresolved external symbol _mexPrintf
cones.obj : error LNK2019: unresolved external symbol _dsyevr referenced in function _projSemiDefiniteCone
cones.obj : error LNK2019: unresolved external symbol _dsyr referenced in function _projSemiDefiniteCone
cones.obj : error LNK2019: unresolved external symbol _dscal referenced in function _projSemiDefiniteCone
cones.obj : error LNK2019: unresolved external symbol _dnrm2 referenced in function _projSemiDefiniteCone
scs.obj : error LNK2019: unresolved external symbol _mexEvalString referenced in function _printFooter
ctrlc.obj : error LNK2019: unresolved external symbol _utIsInterruptPending referenced in function _isInterrupted
ctrlc.obj : error LNK2019: unresolved external symbol _utSetInterruptEnabled referenced in function _endInterruptListener
scs_mex.obj : error LNK2019: unresolved external symbol _mxGetNumberOfDimensions_730 referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxGetDimensions_730 referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxGetIr_730 referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxGetJc_730 referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxIsSparse referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxGetPr referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxSetPr referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxSetM_730 referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxIsEmpty referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxGetField_730 referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxSetField_730 referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxSetN_730 referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxCreateDoubleMatrix_730 referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxCreateString referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mxCreateStructArray_730 referenced in function _mexFunction
scs_mex.obj : error LNK2019: unresolved external symbol _mexErrMsgTxt referenced in function _mexFunction
C:\Program Files\MATLAB\MATLAB Production Server\R2015a\extern\lib\win64\microsoft\libut.lib : warning LNK4272: library machine type 'x64' conflicts with
target machine type 'X86'
C:\Program Files\MATLAB\MATLAB Production Server\R2015a\extern\lib\win64\microsoft\libmwblas.lib : warning LNK4272: library machine type 'x64' conflicts with
target machine type 'X86'
C:\Program Files\MATLAB\MATLAB Production Server\R2015a\extern\lib\win64\microsoft\libmwlapack.lib : warning LNK4272: library machine type 'x64' conflicts
with target machine type 'X86'
C:\Program Files\MATLAB\MATLAB Production Server\R2015a\extern\lib\win64\microsoft\libmx.lib : warning LNK4272: library machine type 'x64' conflicts with
target machine type 'X86'
C:\Program Files\MATLAB\MATLAB Production Server\R2015a\extern\lib\win64\microsoft\libmex.lib : warning LNK4272: library machine type 'x64' conflicts with
target machine type 'X86'
C:\Program Files\MATLAB\MATLAB Production Server\R2015a\extern\lib\win64\microsoft\libmat.lib : warning LNK4272: library machine type 'x64' conflicts with
target machine type 'X86'
E:\Ghafarian\scs-master\matlab\scs_direct.mexw32 : fatal error LNK1120: 28 unresolved externals

Error in compile_direct (line 17)
eval(cmd);

Error in make_scs (line 44)
compile_direct(flags, common_scs);

what is wrong? what should I do?
Thank you very much.

**Comment by bodono** [comment]
That looks like a problem with matlab, since `_mxMalloc` etc. are all matlab library functions. This link might help: http://uk.mathworks.com/matlabcentral/answers/101322-why-do-i-receive-unresolved-external-symbol-errors-when-building-my-project-in-msvc-development-stud

**Comment by hosseinghafarian** [comment]
I changed the default compiler for mex, using mex -setup and make_scs completed successfully. The compiler was setup for mex was Visual studio 2015 which produces the above bug in Matlab 2015a. When I changed it to Visual studio 2013, problem resolved. 
Thank you very much

**Comment by bodono** [comment]
Glad you solved it. By the way, following up on your email about warm-starting, if you want to use warm-starts in the matlab interface for SCS you can do something like the example below, where I pass the solution as a warm-start, you can see terminates on the first iteration, since the warm-start has already solved the problem to the desired accuracy:
```
disp('Example run:');
randn('seed',9)
m = 9;
n = 3;
data.A = sparse(randn(m,n));
data.b = randn(m,1);
data.c = randn(n,1);
cones.l = m;
[x,y,s,info] = scs_indirect(data,cones,[]); % solve cold-start

% pass in solutions as warm-start
data.x = x; % primal variable warm-start
data.y = y; % dual variable warm-start
data.s = s; % primal slack variable warm-start
[x,y,s,info] = scs_indirect(data,cones,[]); % solve, SCS will make use of warm-start in data
```
Output:
```
Example run:
----------------------------------------------------------------------------
	SCS v1.2.1 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2016
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 27, CG tol ~ 1/iter^(2.00)
eps = 1.00e-03, alpha = 1.50, max_iters = 2500, normalize = 1, scale = 1.00
Variables n = 3, constraints m = 9
Cones:	linear vars: 9
Setup time: 3.04e-03s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0|      inf       inf       nan      -inf       inf       inf  1.80e-02 
   100| 1.09e-03  7.42e-04  3.99e-04  1.90e+00  1.90e+00  1.23e-16  5.84e-02 
   120| 5.35e-04  1.11e-04  5.80e-05  1.91e+00  1.91e+00  1.23e-16  1.72e-01 
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 2.07e-01s
	Lin-sys: avg # CG iterations: 2.92, avg solve time: 6.30e-07s
	Cones: avg projection time: 4.74e-08s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 1.1053e-16, dist(y, K*) = 0.0000e+00, s'y/|s||y| = 3.9925e-18
|Ax + s - b|_2 / (1 + |b|_2) = 5.3492e-04
|A'y + c|_2 / (1 + |c|_2) = 1.1124e-04
|c'x + b'y| / (1 + |c'x| + |b'y|) = 5.7962e-05
----------------------------------------------------------------------------
c'x = 1.9056, -b'y = 1.9059
============================================================================
Warm-starting:
----------------------------------------------------------------------------
	SCS v1.2.1 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2016
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 27, CG tol ~ 1/iter^(2.00)
eps = 1.00e-03, alpha = 1.50, max_iters = 2500, normalize = 1, scale = 1.00
Variables n = 3, constraints m = 9
Cones:	linear vars: 9
Setup time: 2.14e-02s
SCS using variable warm-starting
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 5.06e-04  3.19e-04  1.39e-05  1.91e+00  1.91e+00  0.00e+00  3.35e-02 
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 7.13e-02s
	Lin-sys: avg # CG iterations: 1.00, avg solve time: 2.96e-06s
	Cones: avg projection time: 5.00e-07s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 0.0000e+00, dist(y, K*) = 0.0000e+00, s'y/|s||y| = 1.0764e-17
|Ax + s - b|_2 / (1 + |b|_2) = 5.0595e-04
|A'y + c|_2 / (1 + |c|_2) = 3.1945e-04
|c'x + b'y| / (1 + |c'x| + |b'y|) = 1.3856e-05
----------------------------------------------------------------------------
c'x = 1.9057, -b'y = 1.9057
============================================================================
```
