### ISSUE TITLE
Optimization Comments are Inaccurate

### ISSUE THREAD

**Issue by DavidFCrouse** [cvxgrp/scs#58]
The documentation says that the primal problem solved is
minimize        c'x
subject to      Ax + s = b
                s in K

However, when running the solver, it appears that the problem solved is actually
maximize        c'x
subject to      Ax + s = b
                s in K

I think that the comments for which problem is being solved need to be changed.

**Comment by bodono** [comment]
It's attempting the solve `minimize c'x`, do you have an example where it is doing something different?

**Comment by DavidFCrouse** [comment]
A minimal example is just a very simple linear programming example. The example Matlab code below gives the correct solution of x=[0.6;1.8;0;0], where the final two elements are useless helper variables. If one were to flip the sign of c, then the problem would return as unbounded. The problem (as Matlab code) is:

%minimize c'*x
%subject to
%ALeq*x<=bLeq
%x>=0
c=[1;-5];
ALeq=[2,1;
   -1,2];
bLeq=[3;3];

%Transforming into the values needed by the solver, we get
c=-[c;zeros(2,1)];%Note flipping the sign of c
A=[-ALeq,zeros(2,2);
   zeros(2,2),-eye(2,2)];
b=[-bLeq;zeros(2,1)];
cone=[];
cone.l=4;

data.A=sparse(A);
data.b=b;
data.c=c;
[x, y, s, info] = scs_indirect(data, cone,[])

**Comment by bodono** [comment]
The correct way to convert that problem into standard form is the following:
```matlab
A = [ALeq; -eye(2)];
b = [bLeq; zeros(2,1)];
data.A=sparse(A);
data.b=b;
data.c=c;
[x_1, y_1, s_1, info] = scs_indirect(data, cone, []);
```
from which I get
```
>> x_1
x_1 =
    0.6000
    1.8000
```

Your conversion was actually solving
```
minimize -c'x
subject to
Ax >= b
```

The answers coincide because
```
>> inv(ALeq) * bLeq
ans =
    0.6000
    1.8000
```
