### ISSUE TITLE
csc_matlab not working with cvx

### ISSUE THREAD

**Issue by mfalt** [cvxgrp/scs#59]
CVX is not able to load scs_matlab as solver in matlab.
The problem seems to occur in cvx_setup.m line 103
`        nsolvers = [ nsolvers, tsolv ]; %#ok`
because `cvx_scs_matlab` returns a shim with the extra field `shim.config` which is not occuring in the other solvers in `nsolvers`.

I'm running CVX Version 2.1, Build 1110 (66e9a9c).

**Comment by bodono** [comment]
SCS is only compatible with CVX 3.0b, due to some breaking API changes a few months ago, as we mention in the readme.

**Comment by mfalt** [comment]
I had completely missed this in the readme, thanks!

**Comment by bodono** [comment]
Sorry it's not clearer, I will add a comment that prints at the end of the install script, re-opening this as a reminder.
