### ISSUE TITLE
Issue importing scs 1.2.2

### ISSUE THREAD

**Issue by SteveDiamond** [cvxgrp/scs#63]
When I import scs 1.2.2 in OS X I get
```
>>> import scs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scs.py", line 4, in <module>
    import _scs_direct
ImportError: dlopen(/Users/stevend2/anaconda/envs/cvxpy/lib/python2.7/site-packages/scs-1.2.2-py2.7-macosx-10.5-x86_64.egg/_scs_direct.so, 2): Library not loaded: libmkl_intel_lp64.dylib
  Referenced from: /Users/stevend2/anaconda/envs/cvxpy/lib/python2.7/site-packages/scs-1.2.2-py2.7-macosx-10.5-x86_64.egg/_scs_direct.so
  Reason: image not found
```
SCS 1.2.1 works fine.

**Comment by bodono** [comment]
I can't reproduce this for 1.2.2 on OS X. Are you sure 1.2.1 works fine? Nothing about the linking changed in that release. I just made a new release, 1.2.3, does that one work?

**Comment by SteveDiamond** [comment]
I have the same problem with 1.2.3. I'm using Anaconda, so maybe that's causing problems. The linking issue seems related to MKL in Anaconda.

**Comment by bodono** [comment]
Did you check 1.2.1 again by any chance?

**Comment by SteveDiamond** [comment]
1.2.1 still works. Travis CI now has OS X support. Maybe you could use that to test the SCS builds, try it on a clean system?

**Comment by bodono** [comment]
Adding Travis OSX support is a good idea, I'll do that. The fact that 1.2.1 works is worrying, I will look into that too.

**Comment by bodono** [comment]
I just added travis support for OSX, and configured it to use blas/lapack for the first time, so it's testing SDPs now. I think this could be a useful first step for making a conda release.

I uploaded a new version to pip (1.2.5) that includes a hack to get around the MKL bug in scipy, test it out and let me know if it works for you now.

**Comment by SteveDiamond** [comment]
It works! Thanks for figuring this out.
