### ISSUE TITLE
Convergence to zero at certain problem sizes

### ISSUE THREAD

**Issue by jbruer** [cvxgrp/scs#64]
### Short version
When solving the unconstrained trace-norm minimization problem
`minimize_X     (1/2)||X - Z||_F^2 + \lambda ||X||_*`,
the solver (SCS) converges to **X** = **0** for certain sizes of **X** when there exists a nonzero solution. In particular, this appears to occur when **X** is square with side length a power of 2 and at least 256. The matrix **Z** = **X_0** + **W**, where **X_0** is a random rank-1 matrix with unit Frobenius norm, and **W** has iid Normal(0, \sigma^2) entries. The parameter \lambda is computed based on the size of **Z** and the noise level (code below). 

The fact that I'm seeing "convergence to zero" and that it has this power-of-2 dependence made me think something is going on in SCS, but I haven't been able to eliminate CVXPY as the source of the bug. Solving with CVXOPT gobbles up too much memory. Solving this problem with CVX and SCS in MATLAB works as expected, but CVX also passes a different representation to SCS. Maybe @SteveDiamond has some thoughts on this.

### Detailed version
Running Python 3.5.1 (brew installed) on OS X 10.10.5 with these CVXPY prerequisites:
```
CVXcanon (0.0.23.3)
cvxopt (1.1.8)
cvxpy (0.3.9)
ecos (2.0.4)
multiprocess (0.70.4)
numpy (1.11.0)
scipy (0.17.0)
scs (1.2.3)
setuptools (20.3.1)
toolz (0.7.4)
```

``` python
import cvxpy
import numpy as np

SHAPE = (256, 256)
SNR = 10.0  # 10.0 dB SNR
SIGMA = 10.0**(-SNR/20.0)*(1.0/np.sqrt(np.prod(SHAPE)))  # compute noise level
LAMBDA = SIGMA*(np.sqrt(SHAPE[0]) + np.sqrt(SHAPE[1]))  # penalty constant

# Generate a random rank-1 matrix X0, and corrupt it with noise
u = np.random.normal(size=(SHAPE[0], 1))
v = np.random.normal(size=(SHAPE[1], 1))
X0 = np.dot(u, v.T)
X0 = X0/np.linalg.norm(X0, 'fro')  # normalize
Xnoisy = X0 + np.random.normal(scale=SIGMA, size=SHAPE)

# Set up the optimization problem
# minimize_X 0.5*||X - Xnoisy||^2_F + LAMBDA*||X||_*
X = cvxpy.Variable(*SHAPE)
measerr = 0.5*cvxpy.norm(X - Xnoisy, 'fro')**2  # measurement error
reg = LAMBDA*cvxpy.norm(X, 'nuc')  # regularizer (trace norm)
prob = cvxpy.Problem(cvxpy.Minimize(measerr + reg))
prob.solve(solver=cvxpy.SCS, verbose=True)

# Calculate the objective at X0---a feasible point---using cvxpy
objX0 = ((0.5*cvxpy.norm(X0 - Xnoisy, 'fro')**2).value +
         LAMBDA*cvxpy.norm(X0, 'nuc').value)
# Also calculate the objective at zero
obj0 = 0.5*np.linalg.norm(Xnoisy, ord='fro')**2

print('CVXPY status:  {0}'.format(prob.status))
print('objective(X):  {0}'.format(prob.objective.value))
print('objective(0):  {0}'.format(obj0))
print('objective(X0): {0}'.format(objX0))  # X0 is a feasible point
print('||X||_* = {0}'.format(np.linalg.norm(X.value, ord='nuc')))
```

Running an instance of this script returns the following output:
```
----------------------------------------------------------------------------
	SCS v1.2.3 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2016
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 524036
eps = 1.00e-03, alpha = 1.50, max_iters = 2500, normalize = 1, scale = 1.00
Variables n = 327682, constraints m = 393220
Cones:	primal zero / dual free vars: 196352
	soc vars: 65540, soc blks: 2
	sd vars: 131328, sd blks: 1
Setup time: 2.63e-01s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0|      inf       inf       nan      -inf       inf       inf  1.03e-01 
    20| 3.12e-05  4.02e-05  9.86e-06  5.49e-01  5.49e-01  1.16e-16  1.25e+00 
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 1.26e+00s
	Lin-sys: nnz in L factor: 1244938, avg solve time: 8.16e-03s
	Cones: avg projection time: 4.25e-02s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 6.6613e-16, dist(y, K*) = 3.3307e-15, s'y/|s||y| = -3.2417e-16
|Ax + s - b|_2 / (1 + |b|_2) = 3.1215e-05
|A'y + c|_2 / (1 + |c|_2) = 4.0243e-05
|c'x + b'y| / (1 + |c'x| + |b'y|) = 9.8596e-06
----------------------------------------------------------------------------
c'x = 0.5488, -b'y = 0.5488
============================================================================
CVXPY status:  optimal
objective(X):  0.5487381817397832
objective(0):  0.5487508250412936
objective(X0): 0.0894842367535229
||X||_* = 7.490368228752549e-05
```
We compare the objective value with that using the original matrix `X0`, a feasible point, just to illustrate that the solution returned is suboptimal for the original problem. Note that requiring higher accuracy by setting `eps=1e-6` in the options to SCS will push the solution closer to zero. That is, it appears we are really seeing convergence to zero in SCS.

Running with `SHAPE = (257, 257)`, for instance, gives:
```
----------------------------------------------------------------------------
	SCS v1.2.3 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2016
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 594188
eps = 1.00e-03, alpha = 1.50, max_iters = 2500, normalize = 1, scale = 1.00
Variables n = 330247, constraints m = 396298
Cones:	primal zero / dual free vars: 197890
	soc vars: 66053, soc blks: 2
	sd vars: 132355, sd blks: 1
Setup time: 3.25e-01s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0|      inf       inf       nan      -inf       inf       inf  3.48e-01 
    40| 3.23e-04  3.49e-04  4.79e-04  8.80e-02  8.86e-02  7.72e-17  1.09e+01 
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 1.10e+01s
	Lin-sys: nnz in L factor: 1320733, avg solve time: 8.40e-03s
	Cones: avg projection time: 2.50e-01s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 1.4669e-09, dist(y, K*) = 4.4882e-10, s'y/|s||y| = 2.1510e-12
|Ax + s - b|_2 / (1 + |b|_2) = 3.2339e-04
|A'y + c|_2 / (1 + |c|_2) = 3.4862e-04
|c'x + b'y| / (1 + |c'x| + |b'y|) = 4.7882e-04
----------------------------------------------------------------------------
c'x = 0.0880, -b'y = 0.0886
============================================================================
CVXPY status:  optimal
objective(X):  0.08781080164736181
objective(0):  0.5492738765988324
objective(X0): 0.08889587090716308
||X||_* = 0.96174448568897
```
In this case, SCS converges to a nonzero solution that is not demonstrably suboptimal when compared to `X0`.

For square matrices, the issue does not occur for any size until 256^2. It fails at 512^2 and 1024^2 as well. With rectangular matrices, I observe the same behavior at 128x384, for instance.

**Comment by bodono** [comment]
Thanks for flagging this and giving such a detailed description. This is a very strange issue indeed. I added the following lines to your script:
```
data = prob.get_problem_data(cvxpy.SCS)    # get SCS problem data                                       
                                                                                                        
params = {}  # no additional params required                                                            
sol = scs.solve(data, data['dims'], **params)    # solve in SCS                                         
                                                                                                        
from genRandomConeProb import *     # cone projection routines                                          
# do the following because genRandomConeProb doesn't like missing cones                                 
data['dims']['ep'] = 0                                                                                  
data['dims']['ed'] = 0                                                                                  
data['dims']['p'] = {}                                                                                  
                                                                                                        
print('Duality gap:  {0}'.format(np.dot(data['c'], sol['x']) + np.dot(data['b'], sol['y'])))            
print('Primal residual:  {0}'.format(np.linalg.norm(data['A'].dot(sol['x']) + sol['s'] - data['b'])))   
print('Dual residual:  {0}'.format(np.linalg.norm(data['A'].T.dot(sol['y']) + data['c'])))              
                                                                                                        
print('Primal cone error:  {0}'.format(np.linalg.norm(sol['s'] - proj_cone(sol['s'], data['dims']))))   
print('Dual cone error:  {0}'.format(np.linalg.norm(sol['y'] - proj_dual_cone(sol['y'], data['dims']))))
```
CVXPY has a nice feature that you can pull out the data that is getting passed to the solver directly, in the canonical form it accepts. This allows us to talk directly to SCS, and check in python whether the solution it returns is actually optimal or not, given the data it received.

Running with those extra lines, on an example that breaks, I get:
```
Duality gap:  -2.0763261198597505e-05
Primal residual:  8.58649469424906e-05
Dual residual:  6.655642390908208e-05
Primal cone error:  4.664535778086328e-16
Dual cone error:  1.5716250041522723e-16
```
This is basically saying that the solution SCS is finding is close to optimal, to those tolerances, since the KKT conditions say that having those five quantities be zero is necessary and sufficient for global optimality.

Clearly the solution is *not* optimal for the problem you specified however. But this suggests that the problem is likely in cvxpy, rather than SCS, in either the problem transformation or transforming the solution back. @SteveDiamond would you mind taking a look at this to see if my hunch is right? I'm happy to keep digging into SCS if you think the problem is there.

**Comment by bodono** [comment]
I can also reproduce on python 2.7.11. I thought it might have been an integer division issue.

**Comment by jbruer** [comment]
Thanks for taking a look. In the output from SCS, there does appear to be some difference happening in the problem generation/transformation. In the 256^2 case, there are relatively more zeros in the A matrix than in the 257^2 case or for that matter the 128^2 case (a power-of-two that exhibits no issue). At 512^2, another problem case, the same discrepancy exists. I don't recall seeing a discrepancy in the "tree-form" of the problem from CVXPY, but I would need to take another look at that. @SteveDiamond can probably track down where this is happening much faster than I can, but I will try to take a closer look soon.

**Comment by SteveDiamond** [comment]
This is the most bizarre bug I've seen in CVXPY or the solvers. I have no idea what the problem is. I'm not convinced it's CVXPY, since I couldn't find anything in the canonicalization related to powers of two. Here's a simpler example that fails for the same problem sizes:
```
import cvxpy
SHAPE = (256, 256)
X = cvxpy.Variable(*SHAPE)
reg = cvxpy.norm(X, 'nuc')  # regularizer (trace norm)
prob = cvxpy.Problem(cvxpy.Minimize(reg), [X[0,0] >= 1])
prob.solve(solver=cvxpy.SCS, verbose=True)
print('CVXPY status:  {0}'.format(prob.status))
print('objective(X):  {0}'.format(prob.objective.value))
```

**Comment by bodono** [comment]
That minimal example is solved for all sizes up to 256, but returns infeasible for size 256. Examining the tolerances of the certificate SCS returns, with `eps = 1e-9`, I get
```
b'y:  -1.0
Dual residual:  9.25926002537e-14
Dual cone error:  0.0
```
which is extremely high tolerance and clearly a real certificate that the data coming into SCS is infeasible. I dug into @jbruer hint about NNZs in A for sizes 1 up to 300, and got the following plot:

![issue64](https://cloud.githubusercontent.com/assets/555071/14636058/3db3e542-0621-11e6-80a7-5f3aed6c96da.png)

The problem at size 256 has a noticeable deviation from the trend and is the only one that fails. Note that this plot was generated without SCS, it's straight out of CVXPY:
```
import cvxpy                                                        
import numpy as np                                                  
import matplotlib.pyplot as plt                                     
                                                                    
nnzs = []                                                           
for i in range(1, 300):                                             
  SHAPE = (i, i)                                                    
  X = cvxpy.Variable(*SHAPE)                                        
  reg = cvxpy.norm(X, 'nuc')  # regularizer (trace norm)            
  prob = cvxpy.Problem(cvxpy.Minimize(reg), [X[0,0] >= 1])          
                                                                    
  data = prob.get_problem_data(cvxpy.SCS)    # get SCS problem data 
  nnzs.append(len(data['A'].nonzero()[0]))                          
                                                                    
plt.plot(nnzs)                                                      
plt.show()                                                          
```

I really think now that this is something in CVXPY, I have no idea what it could be though.

**Comment by jbruer** [comment]
Note that if you ask for the problem data using CVXOPT as the solver, you also get a similar blip in nnz(A). The actual numbers are different due to the implementation of the SDP.

I've done some more testing and have possibly narrowed down where the issue occurs. Given that this is outside of SCS, I will make an issue over at the CVXPY page with those details. Thanks, @bodono, for looking into this on your end.
