### ISSUE TITLE
include "scs.h" in c++ source code

### ISSUE THREAD

**Issue by wangdingkang** [cvxgrp/scs#65]
I'm trying to use scs in my c++ project, and I have tried different ways to add linker options you mentioned in the manual, but seems it's not working, it can't find the header file.

And actually, I don't find a directory called 'lib' after make the package.

**Comment by bodono** [comment]
When you call `make` it creates an `out` folder with the compiled libraries in it.

**Comment by wangdingkang** [comment]
Thanks, I can compile my project now, btw, do you have any SDP examples or tutorials?

**Comment by bodono** [comment]
Excellent. I'll close this and respond to your other issue.
