### ISSUE TITLE
how to make scs_solve() quieter?

### ISSUE THREAD

**Issue by wangdingkang** [cvxgrp/scs#67]
every time I call scs_solve(), it will output some version info, status, timing info, etc., but I don't need these info, and I need to output some other log info in the console.

So can i let scs_solve() not send messages to console?

**Comment by bodono** [comment]
The Data struct contains a Settings struct, when you pass that in just set Settings member variable verbose = 0:
```
        scs_int verbose;    /* boolean, write out progress: 1 */
```
