### ISSUE TITLE
Change the settings of SCS in CVX

### ISSUE THREAD

**Issue by cek1006** [cvxgrp/scs#71]
Hi, there, 

I want to know how to change the settings of SCS solver in CVX3.0b?

Thanks.

    /* struct containing solver settings */
    struct SCS_SETTINGS {
        /* settings parameters: default suggested input */

        /* these *cannot* change for multiple runs with the same call to scs_init */
        scs_int normalize;  /* boolean, heuristic data rescaling: 1 */
        scs_float scale;    /* if normalized, rescales by this factor: 5 */
        scs_float rho_x;    /* x equality constraint scaling: 1e-3 */

        /* these can change for multiple runs with the same call to scs_init */
        scs_int max_iters;  /* maximum iterations to take: 2500 */
        scs_float eps;      /* convergence tolerance: 1e-3 */
        scs_float alpha;    /* relaxation parameter: 1.8 */
        scs_float cg_rate;  /* for indirect, tolerance goes down like (1/iter)^cg_rate: 2 */
        scs_int verbose;    /* boolean, write out progress: 1 */
        scs_int warm_start; /* boolean, warm start (put initial guess in Sol struct): 0 */
    };

**Comment by bodono** [comment]
[Here](https://github.com/cvxgrp/scs/blob/0ffa9faf93da8f791322ba08643e5a6d098443fb/examples/matlab/run_lasso_ex.m#L49) is an example changing the `eps` and `scale` settings, the others follow the same pattern.
