### ISSUE TITLE
Solving a QP with SCS

### ISSUE THREAD

**Issue by jstraub** [cvxgrp/scs#73]
I am struggling to reformulate a QP to the standard form accepted by SCS.

min x^T Q x + c^T x
s.t. A x <= b

to 

min c^T x + t
s.t. A x + s = b; s <= 0; Q^(1/2) x = w; t <= w^T w

I found several mentions that the constraint on t should be expressed as a rotated second order cone constraint but SCS does not offer such a constraint. On the other hand t <= w^T w looks like a straight forward second order cone constraint. Could you please help clarify how to convert a QP as shown above to a suitable form for SCS?

**Comment by bodono** [comment]
In the [paper](http://www.stanford.edu/~boyd/papers/pdf/scs.pdf) example 6.2 (Lasso) does a similar transformation you might find useful. The other option is to use a parser to do the transformation for you, like CVX (matlab), CVXPY (python), or Convex.jl (julia) for example.

**Comment by jstraub** [comment]
Thank you for the Lasso pointer! I have looked at CVXPY but I am not sure how to get the transformed problem output in a human-readable form?

Looking at the lasso example it is not obvious to me how to convert the norm inequality constraint into a SOC?

|| 1- w          ||
|| 2 ( Fz - g) ||   < = w + 1

would that become:

omega^T omega <= y  (standard SOC)
omega = [ 1-w, 2 (Fz -g ) ]
y = w + 1

**Comment by bodono** [comment]
A standard SOC has ||w|| <= y, not ||w||^2 <= y, which is a small but important difference. You can convert the form given in the paper to the canonical form by introducing new variables and equality constraints (as you are doing, except you have ||omega||^2).

**Comment by jstraub** [comment]
Ahh thank you for pointing the difference with the norms out! I managed to convert the rotated SOC to a standard SOC as in https://people.eecs.berkeley.edu/~elghaoui/Teaching/EE227A/lecture6.pdf and your code solves the QP beautifully. Thank you!

**Comment by bodono** [comment]
Great! Glad to hear it's working for you.
