### ISSUE TITLE
Solve time of SCS

### ISSUE THREAD

**Issue by cek1006** [cvxgrp/scs#75]
How to get the solve time of SCS using CVX in MATLAB? The solve time, which I mean, includes only the time calling SCS, is not the 'cvx_cputime'.

**Comment by bodono** [comment]
SCS called directly returns an `info` struct with the solve and setup times in it. I'm not sure if that propagates though CVX or not, and I don't have a matlab license to test against any more. The other option is to use `evalc` and parse the information out from the string.
