### ISSUE TITLE
SCS optimal solution violates constraints

### ISSUE THREAD

**Issue by vlad17** [cvxgrp/scs#80]
An example I ran right from my homework (minimize the distance between two loci of points, one an ellipsoid and the other a cylinder) violates the ellipsoid constraint by what seems to be more than what should be expected from numerical error for such a small example.

Example code:

    import sys
    import cvxpy
    import numpy as np

    x1, x2 = cvxpy.Variable(3), cvxpy.Variable(3)

    # x1 is in the ellipsoid
    Q = np.diag([4/9, 4, 1/4])
    b = np.array([16/9, 16, 1])
    c = 169/9

    # x2 is in the cylinder
    E = cvxpy.bmat([[1, x2[0], x2[1]], [x2[0], 1, 0.5], [x2[1], 0.5, 1]])

    constraints = [] # constraint list
    constraints.append(cvxpy.quad_form(x1, Q) + x1.T * b + c <= 1)
    constraints.append(cvxpy.lambda_min(E) >= 0)
    constraints.append(x2[2] <= 1)
    constraints.append(x2[2] >= 0)
    objective = cvxpy.Minimize(cvxpy.norm(x1 - x2))
    prob = cvxpy.Problem(objective, constraints)

    print('python', sys.version)
    print('cvxpy', cvxpy.__version__)
    print('numpy', np.__version__)

    for solver in [cvxpy.CVXOPT, cvxpy.SCS]:
        print('solver', solver)
        opt = prob.solve(solver=solver)
        print('    optimal value', opt)
        print('    constriant[0] <= 1 met?', constraints[0].value)
        x1v = np.array(x1.value).reshape(-1)
        print('    x1 =', x1v)
        print('    x1.Q.x1 + x1.b + c =', x1v.dot(Q.dot(x1v)) + x1v.dot(b) + c)

Output trace:

> python 3.5.2 (default, Nov 17 2016, 17:05:23) 
> [GCC 5.4.0 20160609]
> cvxpy 0.4.8
> numpy 1.11.0
> solver CVXOPT
>     optimal value 1.0876269931626734
>     constriant[0] <= 1 met? True
>     x1 = [-1.19565377 -1.82158433 -0.47012681]
>     x1.Q.x1 + x1.b + c = 1.00000009515
> solver SCS
>     optimal value 1.0797732912211049
>     constriant[0] <= 1 met? False
>     x1 = [-1.18735539 -1.81950177 -0.46078029]
>     x1.Q.x1 + x1.b + c = 1.01612499724

**Comment by bodono** [comment]
SCS is a first-order solver, which for the purpose of this conversation means two things: 1) it can solve problems faster than second-order methods, at the expense of some accuracy, and 2) you can have more fine-grain control on the accuracy of the solution you want (at the expense of time for higher accuracy). If I tighten the tolerance asked of the solution from SCS I get the following:

```python
for solver in [cvxpy.CVXOPT, cvxpy.SCS]:                                   
    print('solver', solver)                                                
    opt = prob.solve(solver=solver, eps=1e-6)                              
    print('    optimal value', opt)                                        
    print('    constriant[0] <= 1 met?', constraints[0].value)             
    x1v = np.array(x1.value).reshape(-1)                                   
    print('    x1 =', x1v)                                                 
    print('    x1.Q.x1 + x1.b + c =', x1v.dot(Q.dot(x1v)) + x1v.dot(b) + c)
```
Note the `eps=1e-6` arg, that asks SCS to solve to `1e-6` accuracy (doesn't affect CVXOPT).
```
('solver', 'CVXOPT')                                        
('    optimal value', 0.8663948666848005)                   
('    constriant[0] <= 1 met?', True)                       
('    x1 =', array([-1.0411658 , -1.70245836, -0.3129583 ]))
('    x1.Q.x1 + x1.b + c =', 1.0000000121776225)            
('solver', 'SCS')                                           
('    optimal value', 0.8663907657473714)                   
('    constriant[0] <= 1 met?', True)                       
('    x1 =', array([-1.04112727, -1.70247987, -0.31293279]))
('    x1.Q.x1 + x1.b + c =', 1.0000128530651864)            
```

(For some reason both CVXOPT and SCS get around 0.866 objective, and not the 1.08 you get).

Of course we can tighten even further, setting `eps = 1e-9` gets:
```
('solver', 'CVXOPT')                                        
('    optimal value', 0.8663948666848005)                   
('    constriant[0] <= 1 met?', True)                       
('    x1 =', array([-1.0411658 , -1.70245836, -0.3129583 ]))
('    x1.Q.x1 + x1.b + c =', 1.0000000121776225)            
('solver', 'SCS')                                           
('    optimal value', 0.8663948614936631)                   
('    constriant[0] <= 1 met?', True)                       
('    x1 =', array([-1.04113286, -1.70248125, -0.31293674]))
('    x1.Q.x1 + x1.b + c =', 1.000000023319501)             
```
Now the two solutions are practically identical. In this particular case SCS didn't really need much extra time to get to that accuracy, but in general it would (and you might need to increase `max_iters` too).

**Comment by vlad17** [comment]
OK, glad it was just a problem with my parameter settings. I couldn't find any explicit CVXPY documentation on the SCS parameter settings (the site seems only to have examples), so that's why I didn't know to tune `eps`.

Doesn't it still seem fishy to you that your optimal value is significantly below mine?

**Comment by bodono** [comment]
CVXOPT, a totally different solver, gets the same answer for me, are you sure you got those numbers?

**Comment by vlad17** [comment]
Very. Even my friend confirmed the same results, for the same problem. I think you're running Python 2 based on the print statements, but it shouldn't make a difference.

Here's an interpreter's trace:

    vlad@vlad-T460:~$ python
    Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
    [GCC 5.4.0 20160609] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sys
    >>> import cvxpy
    >>> import numpy as np
    >>> 
    >>> x1, x2 = cvxpy.Variable(3), cvxpy.Variable(3)
    >>> 
    >>> # x1 is in the ellipsoid
    ... Q = np.diag([4/9, 4, 1/4])
    >>> b = np.array([16/9, 16, 1])
    >>> c = 169/9
    >>> 
    >>> # x2 is in the cylinder
    ... E = cvxpy.bmat([[1, x2[0], x2[1]], [x2[0], 1, 0.5], [x2[1], 0.5, 1]])
    >>> 
    >>> constraints = [] # constraint list
    >>> constraints.append(cvxpy.quad_form(x1, Q) + x1.T * b + c <= 1)
    >>> constraints.append(cvxpy.lambda_min(E) >= 0)
    >>> constraints.append(x2[2] <= 1)
    >>> constraints.append(x2[2] >= 0)
    >>> objective = cvxpy.Minimize(cvxpy.norm(x1 - x2))
    >>> prob = cvxpy.Problem(objective, constraints)
    >>> 
    >>> print('python', sys.version)
    python 3.5.2 (default, Nov 17 2016, 17:05:23) 
    [GCC 5.4.0 20160609]
    >>> print('cvxpy', cvxpy.__version__)
    cvxpy 0.4.8
    >>> print('numpy', np.__version__)
    numpy 1.11.0
    >>> 
    >>> for solver in [cvxpy.CVXOPT, cvxpy.SCS]:
    ...     print('solver', solver)
    ...     opt = prob.solve(solver=solver)
    ...     print('    optimal value', opt)
    ...     print('    constriant[0] <= 1 met?', constraints[0].value)
    ...     x1v = np.array(x1.value).reshape(-1)
    ...     print('    x1 =', x1v)
    ...     print('    x1.Q.x1 + x1.b + c =', x1v.dot(Q.dot(x1v)) + x1v.dot(b) + c)
    ... 
    solver CVXOPT
        optimal value 1.0876269931626734
        constriant[0] <= 1 met? True
        x1 = [-1.19565377 -1.82158433 -0.47012681]
        x1.Q.x1 + x1.b + c = 1.00000009515
    solver SCS
        optimal value 1.0797732912211049
        constriant[0] <= 1 met? False
        x1 = [-1.18735539 -1.81950177 -0.46078029]
        x1.Q.x1 + x1.b + c = 1.01612499724
    >>>

**Comment by bodono** [comment]
It's because in python2 the division operator doesn't promote to floats so the code isn't backwards compatible, if I change your ints to floats in the defintion of Q, b, and c then I get:
```
('    optimal value', 1.0876189003982508)
('    constriant[0] <= 1 met?', True)
('    x1 =', array([-1.19562287, -1.82162367, -0.47006008]))
('    x1.Q.x1 + x1.b + c =', 1.0000170949052745)
```

**Comment by vlad17** [comment]
Ah, so it does make a difference :) In any case thanks for notifying me about `eps`.

**Comment by bodono** [comment]
Sure, no problem. You can add `from __future__ import division` to your imports to get python3 style division in python2 if you care about backwards compatibility of the code.
