### ISSUE TITLE
Specify number of threads used by SCS

### ISSUE THREAD

**Issue by nrontsis** [cvxgrp/scs#82]
I noticed, while running on a server with many cores, that SCS uses a lot of threads (I guess something in the order of the cores available?). This can lead to suboptimal performance in some situations. Is there any way to provide the number of threads to be used?

**Comment by bodono** [comment]
You should be able to control them with the `OMP_NUM_THREADS` environment variable, e.g.,
```
export OMP_NUM_THREADS=4
```
before running SCS.

**Comment by nrontsis** [comment]
Thanks :)
