### ISSUE TITLE
Failure: error in acceleration

### ISSUE THREAD

**Issue by nrontsis** [cvxgrp/scs#88]
Thanks for the new release (2.0.0) it really improved the solution time for the problems I am solving.

Sometimes (very occasionally) I get `Failure: error in acceleration`. Are you planning on adding a fallback to "normal" mode when Anderson acceleration fails?

**Comment by bodono** [comment]
Thanks for letting me know, it should be easy to provide a fallback so I will do that asap.

Long-term, the acceleration step can suffer from bad numerics so we need to add some regularization to the linear system we are solving, and that will come soon.

**Comment by nrontsis** [comment]
Awesome, thanks.
