### ISSUE TITLE
SCS compilation on Unix OS

### ISSUE THREAD

**Issue by heshriti** [cvxgrp/scs#90]
I am trying to install SCS in FreeBSD. Unfortunately, am not able to go past the first step in 'make'.  I tried to change the scs.mk file, but still it gives me strange errors.
So, I completely set the flags manually in the scs.mk file. But when I run make, it just does nothing.

Can one of you provide me a standard Makefile (without any OS dependencies) that I can use to run make? 

I have gcc7, lapack and blas installed in my system. 

Thank you,

**Comment by bodono** [comment]
Hi, can you tell me what errors you're seeing?

**Comment by heshriti** [comment]
First when I run make as is:

make: "scs.mk" line ###: Missing dependency operator
make: "scs.mk" line ###: Need an operator

It seems to be complaining wherever the 'ifneq' command is there in scs.mk So I manually commented and set all the flags.

Then make complains :
make: "Makefile" line 25: Need an operator
make: "Makefile" line 29: Need an operator
make: Fatal errors encountered -- cannot continue

Again ifneq problems. So I commented or set flags to use lapack and blas, manually:

Then, no errors, but it just does nothing!!

>make
print-%=

> then I tried to run just the default make, as in:
 
make default
gcc -O2 -pipe -g -Wall -Wwrite-strings -pedantic -funroll-loops -Wstrict-prototypes -I. -Iinclude -Ilinsys -O3 -fPIC  -DDLONG=0 -DCTRLC=1 -DCOPYAMATRIX= -DUSE_LAPACK -c src/scs.c -o src/scs.o
gcc: error trying to exec 'cc1': execvp: No such file or directory
*** Error code 1
-------------------------------------
When I run the command manually, it seems to be ok:

> gcc -g -Wall -Wwrite-strings -pedantic -funroll-loops -Wstrict-prototypes -I. -Iinclude -Ilinsys -O3 -fPIC  -DCTRLC=1  -DCOPYAMATRIX=1  -DGPU_TRANSPOSE_MAT=1  -DUSE_LAPACK   -c -o src/cs.o src/cs.c
> ls src/
accel.c        cs.c           ctrlc.c        normalize.c    scs.c          
cones.c        cs.o           linalg.c       scs_version.c  util.c


-----

So I just need the sequence of full commands to be run so I have the full SCS package. Alternatively, the core unix Makefile. Any thoughts?

**Comment by bodono** [comment]
Ok, I don't know much about the FreeBSD make, could you try using the GNU make by invoking `gmake` and see if that works?

**Comment by heshriti** [comment]
I tried gmake on the scs original Makefile and scs.mk files.  It is giving the same error as the 'make default' over the manual amended files above.

> gmake
gcc -g -Wall -Wwrite-strings -pedantic -funroll-loops -Wstrict-prototypes -I. -Iinclude -Ilinsys -O3 -fPIC  -DCTRLC=1  -DCOPYAMATRIX=1  -DGPU_TRANSPOSE_MAT=1  -DUSE_LAPACK   -c -o src/scs.o src/scs.c
gcc: error trying to exec 'cc1': execvp: No such file or directory
gmake: *** [<builtin>: src/scs.o] Error 1

**Comment by bodono** [comment]
I did a quick search for that error and I found some hits that may help you:

https://stackoverflow.com/questions/11912878/gcc-error-gcc-error-trying-to-exec-cc1-execvp-no-such-file-or-directory

https://stackoverflow.com/questions/8878676/compile-error-g-error-trying-to-exec-cc1plus-execvp-no-such-file-or-dir

Sounds like gcc isn't fully installed, or that some of the components it needs are not in your PATH. Another option would be to use clang. On my ubuntu and mac systems to use clang all I have to do is `make CC=clang`, in your case swap `make` for `gmake`, hopefully the command line arg will pass down correctly too.

**Comment by heshriti** [comment]
Thanks. Yes, that helped.

I had to edit the BLASLD flags in scs.mk file to get this working:

....
 BLASLDFLAGS = -lblas -llapack -L/usr/local/lib/gcc7 -Wl,-rpath=/usr/local/lib/gcc7 #-lgfortran
......

gmake CC=clang

worked :)

********
Successfully compiled scs, copyright Brendan O'Donoghue 2012.
To test, type 'out/demo_socp_indirect' to solve a random SOCP.

Compiled with blas and lapack, can solve LPs, SOCPs, SDPs, ECPs, and PCPs
**********************************************************************************

One thing, can you tell me the correct place to add the gcc flags: -L/usr/local/lib/gcc7 -Wl,-rpath=/usr/local/lib/gcc7 

Thanks.

**Comment by bodono** [comment]
Great! Glad to hear it's working for you. You can pass additional flags using CFLAGS environment variable (or you can just edit CFLAGS in scs.mk if that's easier), so something like:
```
gmake CC=clang CFLAGS="-L/usr/local/lib/gcc7 -Wl,-rpath=/usr/local/lib/gcc7"
```
(I just pushed a fix that makes this actually work from the command line, so you'll need to do a pull first).

**Comment by bodono** [comment]
By the way, you can do the same thing for the BLASLDFLAGS, so:
```
gmake CC=clang BLASLDFLAGS="-lblas -llapack -L/usr/local/lib/gcc7 -Wl,-rpath=/usr/local/lib/gcc7"

```
