### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by heshriti** [cvxgrp/scs#92]
Hi,

Are there some examples for using SCS in C? I probably am looking at the wrong place- wasn't finding much except the one/two liners in the github main page.

Thank you.

**Comment by bodono** [comment]
The tests have some examples, e.g.

https://github.com/cvxgrp/scs/blob/master/test/problems/rob_gauss_cov_est.h

and 

https://github.com/cvxgrp/scs/blob/master/test/problems/small_lp.h
