### ISSUE TITLE
What operations cause memory jump?

### ISSUE THREAD

**Issue by sarahwie** [cvxgrp/scs#95]
I'm running a bi-convex matrix decomposition problem using CVXPY/DMCP and calling the SCS solver for the fixed set convex optimization problems. My input matrix isn't too large (300 * 5000), with decomposition matrices of (300 * 300) and (300 * 5000). The process allocates an insane amount of memory at initialization, but doesn't use much during problem setup and creation of matrices, until SCS is called for a given fixed set, at which point it spikes insanely and overloads my system. What parts of the computation are causing this, and are there any ways to mitigate this problem? 

I should also note that I enabled GPU functionality, hoping to move everything to the GPU memory, but it still overloads my system RAM despite barely using any of the available GPU memory up to the point of overload.

**Comment by bodono** [comment]
Do you have any code for this that I can run myself? Failing that can you post what SCS outputs to stdout when it starts up (you might have to pass verbose=True to cvxpy)?

**Comment by sarahwie** [comment]
Sure- working on generating a minimum viable example.

**Comment by sarahwie** [comment]
Ok, here's one. I modified the `bcd` method call and call to cvxpy solve to pass in `gpu` and `num_cores` flags to SCS. 

```
from cvxpy import *
import numpy as np
import dmcp

# Generate data
k = 300 #X is [k*n], A is [p*n], D is [k*p]
p = 300
n = 5000

np.random.seed(1)
D = np.random.rand(k, p)
# normalize D so that each column has L2 norm <= 1
for i in range(p):
    D[:, i] = D[:, i] / np.sqrt(sum(D[:, i]**2))

A = np.identity(min(p, n))
B = np.tile(A, int(np.ceil(n/p)))
A = B[:, 0:n]

X = np.matmul(D, A)

k, n = X.shape

#Create Variables/Parameters
D_var = Variable(k, p)
A_var = Variable(p, n)
gamma_par = Parameter(sign="positive")

#initialize Variable/Parameter values
D_var.value = D
A_var.value = A
gamma_par.value = 0.1

objective = Minimize(sum_entries(square(D_var*A_var - X)) + gamma_par*norm(A_var, 1))
constraints = [norm(D_var[:, p_iter], 2) <= 1 for p_iter in range(p)]
prob = Problem(objective, constraints)

prob.solve(method='bcd', solver='SCS', max_iter=100, ep=1e-05, num_cores=1, gpu=True)

```

**Comment by bodono** [comment]
Thanks for the example. I ran it, and the first iteration had 4502404 non-zeros in the data matrix, but the second iteration had 442081804 non-zeros, which is 100x the first and the data matrix is about 8G on it's own. The total memory usage got up to 60Gb on my machine, probably due to the all the extra stuff going on, a lot of which is python / numpy memory. Basically the reason is due to the blowup of the amount of data after the first iteration. Possibly you can reduce the problem size at the second step?

**Comment by sarahwie** [comment]
Ah, I see. I was hoping it would scale to my problem size, but it seems like that is not the case. Thanks for the feedback!

**Comment by bodono** [comment]
If you have the memory then the problems are getting solved in about 20-25 minutes. You can also compile SCS to be more memory efficient by not copying the data matrix, which it does for safety, that would shave off a few Gb. You can do that by deleting the COPYAMATRIX statement here:
https://github.com/bodono/scs-python/blob/master/setup.py#L164
and running `python setup.py install` again. Although I think a lot of the memory overhead is not actually SCS.
