### ISSUE TITLE
Setting precision for CVXPY solver

### ISSUE THREAD

**Issue by DonghanHe** [cvxgrp/scs#96]
I am solving max cut problems using SDP relaxation in CVXPY with the SCS solver. However, I have noticed that for a small graph (20*20), SCS and CVXOPT generate very different cuts after random rounding (with CVXOPT getting the better obj),. Thus I would like to know how to set the accuracy/precision on the SCS solver. 

(briefly skimming through your paper I understand that it will require much more time to achieve high accuracy, but I am willing to pay that price just for experimentation sake, so that I can comfortably employ your solver for my eventual objective - same algorithm on a 500*500 graph)

**Comment by bodono** [comment]
In cvxpy you can do:
```python
problem.solve(solver=cvxpy.SCS, eps=1e-5)
```
and decrease `eps` to return solutions closer to optimal. Sometimes I find it useful to pass in `verbose=True` too, just to see what's going on.
